package gg.rsmod.plugins.content.items.potion

import gg.rsmod.plugins.api.cfg.Items

enum class Potion(
    val item: Int,
    val replacement: Int = -1,
    val potionType: PotionType,
    /** Barbarian mix: Hitpoints healed on top of the base potion's effect ([BarbarianMixes]); 0 = not a 667 barbarian mix. */
    val mixHeal: Int = 0,
) {
    STRENGTH_POTION4(
        item = Items.STRENGTH_POTION_4,
        replacement = Items.STRENGTH_POTION_3,
        potionType = PotionType.STRENGTH,
    ),
    STRENGTH_POTION3(
        item = Items.STRENGTH_POTION_3,
        replacement = Items.STRENGTH_POTION_2,
        potionType = PotionType.STRENGTH,
    ),
    STRENGTH_POTION2(
        item = Items.STRENGTH_POTION_2,
        replacement = Items.STRENGTH_POTION_1,
        potionType = PotionType.STRENGTH,
    ),
    STRENGTH_POTION1(
        item = Items.STRENGTH_POTION_1,
        replacement = Items.VIAL,
        potionType = PotionType.STRENGTH,
    ),

    SUPER_STRENGTH4(
        item = Items.SUPER_STRENGTH_4,
        replacement = Items.SUPER_STRENGTH_3,
        potionType = PotionType.SUPER_STRENGTH,
    ),
    SUPER_STRENGTH3(
        item = Items.SUPER_STRENGTH_3,
        replacement = Items.SUPER_STRENGTH_2,
        potionType = PotionType.SUPER_STRENGTH,
    ),
    SUPER_STRENGTH2(
        item = Items.SUPER_STRENGTH_2,
        replacement = Items.SUPER_STRENGTH_1,
        potionType = PotionType.SUPER_STRENGTH,
    ),
    SUPER_STRENGTH1(
        item = Items.SUPER_STRENGTH_1,
        replacement = Items.VIAL,
        potionType = PotionType.SUPER_STRENGTH,
    ),

    ATTACK4(item = Items.ATTACK_POTION_4, replacement = Items.ATTACK_POTION_3, potionType = PotionType.ATTACK),
    ATTACK3(item = Items.ATTACK_POTION_3, replacement = Items.ATTACK_POTION_2, potionType = PotionType.ATTACK),
    ATTACK2(item = Items.ATTACK_POTION_2, replacement = Items.ATTACK_POTION_1, potionType = PotionType.ATTACK),
    ATTACK1(item = Items.ATTACK_POTION_1, replacement = Items.VIAL, potionType = PotionType.ATTACK),

    SUPER_ATTACK4(
        item = Items.SUPER_ATTACK_4,
        replacement = Items.SUPER_ATTACK_3,
        potionType = PotionType.SUPER_ATTACK,
    ),
    SUPER_ATTACK3(
        item = Items.SUPER_ATTACK_3,
        replacement = Items.SUPER_ATTACK_2,
        potionType = PotionType.SUPER_ATTACK,
    ),
    SUPER_ATTACK2(
        item = Items.SUPER_ATTACK_2,
        replacement = Items.SUPER_ATTACK_1,
        potionType = PotionType.SUPER_ATTACK,
    ),
    SUPER_ATTACK1(
        item = Items.SUPER_ATTACK_1,
        replacement = Items.VIAL,
        potionType = PotionType.SUPER_ATTACK,
    ),

    DEFENCE_POTION4(
        item = Items.DEFENCE_POTION_4,
        replacement = Items.DEFENCE_POTION_3,
        potionType = PotionType.DEFENCE,
    ),
    DEFENCE_POTION3(
        item = Items.DEFENCE_POTION_3,
        replacement = Items.DEFENCE_POTION_2,
        potionType = PotionType.DEFENCE,
    ),
    DEFENCE_POTION2(
        item = Items.DEFENCE_POTION_2,
        replacement = Items.DEFENCE_POTION_1,
        potionType = PotionType.DEFENCE,
    ),
    DEFENCE_POTION1(
        item = Items.DEFENCE_POTION_1,
        replacement = Items.VIAL,
        potionType = PotionType.DEFENCE,
    ),

    SUPER_DEFENCE4(
        item = Items.SUPER_DEFENCE_4,
        replacement = Items.SUPER_DEFENCE_3,
        potionType = PotionType.SUPER_DEFENCE,
    ),
    SUPER_DEFENCE3(
        item = Items.SUPER_DEFENCE_3,
        replacement = Items.SUPER_DEFENCE_2,
        potionType = PotionType.SUPER_DEFENCE,
    ),
    SUPER_DEFENCE2(
        item = Items.SUPER_DEFENCE_2,
        replacement = Items.SUPER_DEFENCE_1,
        potionType = PotionType.SUPER_DEFENCE,
    ),
    SUPER_DEFENCE1(
        item = Items.SUPER_DEFENCE_1,
        replacement = Items.VIAL,
        potionType = PotionType.SUPER_DEFENCE,
    ),

    RANGING_POTION4(
        item = Items.RANGING_POTION_4,
        replacement = Items.RANGING_POTION_3,
        potionType = PotionType.RANGING,
    ),
    RANGING_POTION3(
        item = Items.RANGING_POTION_3,
        replacement = Items.RANGING_POTION_2,
        potionType = PotionType.RANGING,
    ),
    RANGING_POTION2(
        item = Items.RANGING_POTION_2,
        replacement = Items.RANGING_POTION_1,
        potionType = PotionType.RANGING,
    ),
    RANGING_POTION1(
        item = Items.RANGING_POTION_1,
        replacement = Items.VIAL,
        potionType = PotionType.RANGING,
    ),

    MAGIC_POTION4(item = Items.MAGIC_POTION_4, replacement = Items.MAGIC_POTION_3, potionType = PotionType.MAGIC),
    MAGIC_POTION3(item = Items.MAGIC_POTION_3, replacement = Items.MAGIC_POTION_2, potionType = PotionType.MAGIC),
    MAGIC_POTION2(item = Items.MAGIC_POTION_2, replacement = Items.MAGIC_POTION_1, potionType = PotionType.MAGIC),
    MAGIC_POTION1(item = Items.MAGIC_POTION_1, replacement = Items.VIAL, potionType = PotionType.MAGIC),

    FISHING4(item = Items.FISHING_POTION_4, replacement = Items.FISHING_POTION_3, potionType = PotionType.FISHING),
    FISHING3(item = Items.FISHING_POTION_3, replacement = Items.FISHING_POTION_2, potionType = PotionType.FISHING),
    FISHING2(item = Items.FISHING_POTION_2, replacement = Items.FISHING_POTION_1, potionType = PotionType.FISHING),
    FISHING1(item = Items.FISHING_POTION_1, replacement = Items.VIAL, potionType = PotionType.FISHING),
    AGILITY4(item = Items.AGILITY_POTION_4, replacement = Items.AGILITY_POTION_3, potionType = PotionType.AGILITY),
    AGILITY3(item = Items.AGILITY_POTION_3, replacement = Items.AGILITY_POTION_2, potionType = PotionType.AGILITY),
    AGILITY2(item = Items.AGILITY_POTION_2, replacement = Items.AGILITY_POTION_1, potionType = PotionType.AGILITY),
    AGILITY1(item = Items.AGILITY_POTION_1, replacement = Items.VIAL, potionType = PotionType.AGILITY),
    HUNTER4(item = Items.HUNTER_POTION_4, replacement = Items.HUNTER_POTION_3, potionType = PotionType.HUNTER),
    HUNTER3(item = Items.HUNTER_POTION_3, replacement = Items.HUNTER_POTION_2, potionType = PotionType.HUNTER),
    HUNTER2(item = Items.HUNTER_POTION_2, replacement = Items.HUNTER_POTION_1, potionType = PotionType.HUNTER),
    HUNTER1(item = Items.HUNTER_POTION_1, replacement = Items.VIAL, potionType = PotionType.HUNTER),
    CRAFTING4(item = Items.CRAFTING_POTION_4, replacement = Items.CRAFTING_POTION_3, potionType = PotionType.CRAFTING),
    CRAFTING3(item = Items.CRAFTING_POTION_3, replacement = Items.CRAFTING_POTION_2, potionType = PotionType.CRAFTING),
    CRAFTING2(item = Items.CRAFTING_POTION_2, replacement = Items.CRAFTING_POTION_1, potionType = PotionType.CRAFTING),
    CRAFTING1(item = Items.CRAFTING_POTION_1, replacement = Items.VIAL, potionType = PotionType.CRAFTING),

    FLETCHING_POTION4(
        item = Items.FLETCHING_POTION_4,
        replacement = Items.FLETCHING_POTION_3,
        potionType = PotionType.FLETCHING,
    ),
    FLETCHING_POTION3(
        item = Items.FLETCHING_POTION_3,
        replacement = Items.FLETCHING_POTION_2,
        potionType = PotionType.FLETCHING,
    ),
    FLETCHING_POTION2(
        item = Items.FLETCHING_POTION_2,
        replacement = Items.FLETCHING_POTION_1,
        potionType = PotionType.FLETCHING,
    ),
    // RCV-010 A3: every other one-dose potion leaves a vial; this one had no replacement and vanished.
    FLETCHING_POTION1(item = Items.FLETCHING_POTION_1, replacement = Items.VIAL, potionType = PotionType.FLETCHING),

    COMBAT4(item = Items.COMBAT_POTION_4, replacement = Items.COMBAT_POTION_3, potionType = PotionType.COMBAT),
    COMBAT3(item = Items.COMBAT_POTION_3, replacement = Items.COMBAT_POTION_2, potionType = PotionType.COMBAT),
    COMBAT2(item = Items.COMBAT_POTION_2, replacement = Items.COMBAT_POTION_1, potionType = PotionType.COMBAT),
    COMBAT1(item = Items.COMBAT_POTION_1, replacement = Items.VIAL, potionType = PotionType.COMBAT),

    RESTORE4(item = Items.RESTORE_POTION_4, replacement = Items.RESTORE_POTION_3, potionType = PotionType.RESTORE),
    RESTORE3(item = Items.RESTORE_POTION_3, replacement = Items.RESTORE_POTION_2, potionType = PotionType.RESTORE),
    RESTORE2(item = Items.RESTORE_POTION_2, replacement = Items.RESTORE_POTION_1, potionType = PotionType.RESTORE),
    RESTORE1(item = Items.RESTORE_POTION_1, replacement = Items.VIAL, potionType = PotionType.RESTORE),

    SUPER_RESTORE4(
        item = Items.SUPER_RESTORE_4,
        replacement = Items.SUPER_RESTORE_3,
        potionType = PotionType.SUPER_RESTORE,
    ),
    SUPER_RESTORE3(
        item = Items.SUPER_RESTORE_3,
        replacement = Items.SUPER_RESTORE_2,
        potionType = PotionType.SUPER_RESTORE,
    ),
    SUPER_RESTORE2(
        item = Items.SUPER_RESTORE_2,
        replacement = Items.SUPER_RESTORE_1,
        potionType = PotionType.SUPER_RESTORE,
    ),
    SUPER_RESTORE1(
        item = Items.SUPER_RESTORE_1,
        replacement = Items.VIAL,
        potionType = PotionType.SUPER_RESTORE,
    ),

    SUMMONING_POTION5(
        item = Items.SUMMONING_POTION_5,
        replacement = Items.SUMMONING_POTION_4_14279,
        potionType = PotionType.SUMMONING,
    ),
    SUMMONING_POTION4(
        item = Items.SUMMONING_POTION_4,
        replacement = Items.SUMMONING_POTION_3,
        potionType = PotionType.SUMMONING,
    ),
    SUMMONING_POTION4_ALT(
        item = Items.SUMMONING_POTION_4_14279,
        replacement = Items.SUMMONING_POTION_3_14281,
        potionType = PotionType.SUMMONING,
    ),
    SUMMONING_POTION3(
        item = Items.SUMMONING_POTION_3,
        replacement = Items.SUMMONING_POTION_2,
        potionType = PotionType.SUMMONING,
    ),
    SUMMONING_POTION3_ALT(
        item = Items.SUMMONING_POTION_3_14281,
        replacement = Items.SUMMONING_POTION_2_14283,
        potionType = PotionType.SUMMONING,
    ),
    SUMMONING_POTION2(
        item = Items.SUMMONING_POTION_2,
        replacement = Items.SUMMONING_POTION_1,
        potionType = PotionType.SUMMONING,
    ),
    SUMMONING_POTION2_ALT(
        item = Items.SUMMONING_POTION_2_14283,
        replacement = Items.SUMMONING_POTION_1_14285,
        potionType = PotionType.SUMMONING,
    ),
    SUMMONING_POTION1(
        item = Items.SUMMONING_POTION_1,
        replacement = Items.VIAL,
        potionType = PotionType.SUMMONING,
    ),
    SUMMONING_POTION1_ALT(
        item = Items.SUMMONING_POTION_1_14285,
        replacement = Items.VIAL,
        potionType = PotionType.SUMMONING,
    ),

    PRAYER4(
        item = Items.PRAYER_POTION_4,
        replacement =
            Items.PRAYER_POTION_3,
        potionType = PotionType.PRAYER,
    ),
    PRAYER3(
        item = Items.PRAYER_POTION_3,
        replacement = Items.PRAYER_POTION_2,
        potionType = PotionType.PRAYER,
    ),
    PRAYER2(
        item = Items.PRAYER_POTION_2,
        replacement = Items.PRAYER_POTION_1,
        potionType = PotionType.PRAYER,
    ),
    PRAYER1(
        item = Items.PRAYER_POTION_1,
        replacement = Items.VIAL,
        potionType = PotionType.PRAYER,
    ),

    SUPER_PRAYER4(
        item = Items.SUPER_PRAYER_4,
        replacement = Items.SUPER_PRAYER_3,
        potionType = PotionType.SUPER_PRAYER,
    ),
    SUPER_PRAYER3(
        item = Items.SUPER_PRAYER_3,
        replacement = Items.SUPER_PRAYER_2,
        potionType = PotionType.SUPER_PRAYER,
    ),
    SUPER_PRAYER2(
        item = Items.SUPER_PRAYER_2,
        replacement = Items.SUPER_PRAYER_1,
        potionType = PotionType.SUPER_PRAYER,
    ),
    SUPER_PRAYER1(
        item = Items.SUPER_PRAYER_1,
        replacement = Items.VIAL,
        potionType = PotionType.SUPER_PRAYER,
    ),

    SARADOMIN_BREW4(
        item = Items.SARADOMIN_BREW_4,
        replacement = Items.SARADOMIN_BREW_3,
        potionType = PotionType.SARADOMIN_BREW,
    ),
    SARADOMIN_BREW3(
        item = Items.SARADOMIN_BREW_3,
        replacement = Items.SARADOMIN_BREW_2,
        potionType = PotionType.SARADOMIN_BREW,
    ),
    SARADOMIN_BREW2(
        item = Items.SARADOMIN_BREW_2,
        replacement = Items.SARADOMIN_BREW_1,
        potionType = PotionType.SARADOMIN_BREW,
    ),
    SARADOMIN_BREW1(
        item = Items.SARADOMIN_BREW_1,
        replacement = Items.VIAL,
        potionType = PotionType.SARADOMIN_BREW,
    ),

    // TODO: Formulas for alcoholic beverages
    BEER(
        item = Items.BEER,
        replacement = Items.BEER_GLASS,
        potionType = PotionType.BEER,
    ),
    JUG_OF_WINE(
        item = Items.JUG_OF_WINE,
        replacement = Items.HALF_FULL_WINE_JUG,
        potionType = PotionType.JUG_OF_WINE,
    ),
    HALF_FULL_WINE_JUG(
        item = Items.HALF_FULL_WINE_JUG,
        replacement = Items.JUG,
        potionType = PotionType.HALF_FULL_WINE_JUG,
    ),
    WIZARDS_MIND_BOMB(
        item = Items.WIZARDS_MIND_BOMB,
        replacement = Items.BEER_GLASS,
        potionType = PotionType.WIZARDS_MIND_BOMB,
    ),
    DWARVEN_STOUT(
        item = Items.DWARVEN_STOUT,
        replacement = Items.BEER_GLASS,
        potionType = PotionType.DWARVEN_STOUT,
    ),
    ASGARNIAN_ALE(
        item = Items.ASGARNIAN_ALE,
        replacement = Items.BEER_GLASS,
        potionType = PotionType.ASGARNIAN_ALE,
    ),

    ANTIPOISON4(
        item = Items.ANTIPOISON_4,
        replacement = Items.ANTIPOISON_3,
        potionType = PotionType.ANTIPOISON,
    ),
    ANTIPOISON3(
        item = Items.ANTIPOISON_3,
        replacement = Items.ANTIPOISON_2,
        potionType = PotionType.ANTIPOISON,
    ),
    ANTIPOISON2(
        item = Items.ANTIPOISON_2,
        replacement = Items.ANTIPOISON_1,
        potionType = PotionType.ANTIPOISON,
    ),
    ANTIPOISON1(
        item = Items.ANTIPOISON_1,
        replacement = Items.VIAL,
        potionType = PotionType.ANTIPOISON,
    ),

    SUPER_ANTIPOISON4(
        item = Items.SUPER_ANTIPOISON_4,
        replacement = Items.SUPER_ANTIPOISON_3,
        potionType = PotionType.SUPER_ANTIPOISON,
    ),
    SUPER_ANTIPOISON3(
        item = Items.SUPER_ANTIPOISON_3,
        replacement = Items.SUPER_ANTIPOISON_2,
        potionType = PotionType.SUPER_ANTIPOISON,
    ),
    SUPER_ANTIPOISON2(
        item = Items.SUPER_ANTIPOISON_2,
        replacement = Items.SUPER_ANTIPOISON_1,
        potionType = PotionType.SUPER_ANTIPOISON,
    ),
    SUPER_ANTIPOISON1(
        item = Items.SUPER_ANTIPOISON_1,
        replacement = Items.VIAL,
        potionType = PotionType.SUPER_ANTIPOISON,
    ),
    ANTIFIRE4(
        item = Items.ANTIFIRE_4,
        replacement = Items.ANTIFIRE_3,
        potionType = PotionType.ANTIFIRE,
    ),
    ANTIFIRE3(
        item = Items.ANTIFIRE_3,
        replacement = Items.ANTIFIRE_2,
        potionType = PotionType.ANTIFIRE,
    ),
    ANTIFIRE2(
        item = Items.ANTIFIRE_2,
        replacement = Items.ANTIFIRE_1,
        potionType = PotionType.ANTIFIRE,
    ),
    ANTIFIRE1(
        item = Items.ANTIFIRE_1,
        replacement = Items.VIAL,
        potionType = PotionType.ANTIFIRE,
    ),

    SUPER_ANTIFIRE4(
        item = Items.SUPER_ANTIFIRE_4,
        replacement = Items.SUPER_ANTIFIRE_3,
        potionType = PotionType.SUPER_ANTIFIRE,
    ),
    SUPER_ANTIFIRE3(
        item = Items.SUPER_ANTIFIRE_3,
        replacement = Items.SUPER_ANTIFIRE_2,
        potionType = PotionType.SUPER_ANTIFIRE,
    ),
    SUPER_ANTIFIRE2(
        item = Items.SUPER_ANTIFIRE_2,
        replacement = Items.SUPER_ANTIFIRE_1,
        potionType = PotionType.SUPER_ANTIFIRE,
    ),
    SUPER_ANTIFIRE1(
        item = Items.SUPER_ANTIFIRE_1,
        replacement = Items.VIAL,
        potionType = PotionType.SUPER_ANTIFIRE,
    ),

    ENERGY4(
        item = Items.ENERGY_POTION_4,
        replacement = Items.ENERGY_POTION_3,
        potionType = PotionType.ENERGY,
    ),
    ENERGY3(
        item = Items.ENERGY_POTION_3,
        replacement = Items.ENERGY_POTION_2,
        potionType = PotionType.ENERGY,
    ),
    ENERGY2(
        item = Items.ENERGY_POTION_2,
        replacement = Items.ENERGY_POTION_1,
        potionType = PotionType.ENERGY,
    ),
    ENERGY1(
        item = Items.ENERGY_POTION_1,
        replacement = Items.VIAL,
        potionType = PotionType.ENERGY,
    ),

    // RCV-010 A3: 667 dose potions (Novite `Pots.Pot` ids, Items.kt constants) that had no drink handler.
    SUPER_ENERGY4(item = Items.SUPER_ENERGY_4, replacement = Items.SUPER_ENERGY_3, potionType = PotionType.SUPER_ENERGY),
    SUPER_ENERGY3(item = Items.SUPER_ENERGY_3, replacement = Items.SUPER_ENERGY_2, potionType = PotionType.SUPER_ENERGY),
    SUPER_ENERGY2(item = Items.SUPER_ENERGY_2, replacement = Items.SUPER_ENERGY_1, potionType = PotionType.SUPER_ENERGY),
    SUPER_ENERGY1(item = Items.SUPER_ENERGY_1, replacement = Items.VIAL, potionType = PotionType.SUPER_ENERGY),
    ZAMORAK_BREW4(item = Items.ZAMORAK_BREW_4, replacement = Items.ZAMORAK_BREW_3, potionType = PotionType.ZAMORAK_BREW),
    ZAMORAK_BREW3(item = Items.ZAMORAK_BREW_3, replacement = Items.ZAMORAK_BREW_2, potionType = PotionType.ZAMORAK_BREW),
    ZAMORAK_BREW2(item = Items.ZAMORAK_BREW_2, replacement = Items.ZAMORAK_BREW_1, potionType = PotionType.ZAMORAK_BREW),
    ZAMORAK_BREW1(item = Items.ZAMORAK_BREW_1, replacement = Items.VIAL, potionType = PotionType.ZAMORAK_BREW),
    EXTREME_MAGIC4(item = Items.EXTREME_MAGIC_4, replacement = Items.EXTREME_MAGIC_3, potionType = PotionType.EXTREME_MAGIC),
    EXTREME_MAGIC3(item = Items.EXTREME_MAGIC_3, replacement = Items.EXTREME_MAGIC_2, potionType = PotionType.EXTREME_MAGIC),
    EXTREME_MAGIC2(item = Items.EXTREME_MAGIC_2, replacement = Items.EXTREME_MAGIC_1, potionType = PotionType.EXTREME_MAGIC),
    EXTREME_MAGIC1(item = Items.EXTREME_MAGIC_1, replacement = Items.VIAL, potionType = PotionType.EXTREME_MAGIC),
    SANFEW_SERUM4(item = Items.SANFEW_SERUM_4, replacement = Items.SANFEW_SERUM_3, potionType = PotionType.SANFEW_SERUM),
    SANFEW_SERUM3(item = Items.SANFEW_SERUM_3, replacement = Items.SANFEW_SERUM_2, potionType = PotionType.SANFEW_SERUM),
    SANFEW_SERUM2(item = Items.SANFEW_SERUM_2, replacement = Items.SANFEW_SERUM_1, potionType = PotionType.SANFEW_SERUM),
    SANFEW_SERUM1(item = Items.SANFEW_SERUM_1, replacement = Items.VIAL, potionType = PotionType.SANFEW_SERUM),
    ANTIPOISON_PLUS4(item = Items.ANTIPOISON_4_5943, replacement = Items.ANTIPOISON_3_5945, potionType = PotionType.ANTIPOISON_PLUS),
    ANTIPOISON_PLUS3(item = Items.ANTIPOISON_3_5945, replacement = Items.ANTIPOISON_2_5947, potionType = PotionType.ANTIPOISON_PLUS),
    ANTIPOISON_PLUS2(item = Items.ANTIPOISON_2_5947, replacement = Items.ANTIPOISON_1_5949, potionType = PotionType.ANTIPOISON_PLUS),
    ANTIPOISON_PLUS1(item = Items.ANTIPOISON_1_5949, replacement = Items.VIAL, potionType = PotionType.ANTIPOISON_PLUS),
    ANTIPOISON_PLUS_PLUS4(item = Items.ANTIPOISON_4_5952, replacement = Items.ANTIPOISON_3_5954, potionType = PotionType.ANTIPOISON_PLUS_PLUS),
    ANTIPOISON_PLUS_PLUS3(item = Items.ANTIPOISON_3_5954, replacement = Items.ANTIPOISON_2_5956, potionType = PotionType.ANTIPOISON_PLUS_PLUS),
    ANTIPOISON_PLUS_PLUS2(item = Items.ANTIPOISON_2_5956, replacement = Items.ANTIPOISON_1_5958, potionType = PotionType.ANTIPOISON_PLUS_PLUS),
    ANTIPOISON_PLUS_PLUS1(item = Items.ANTIPOISON_1_5958, replacement = Items.VIAL, potionType = PotionType.ANTIPOISON_PLUS_PLUS),
    MAGIC_ESSENCE4(item = Items.MAGIC_ESSENCE_4, replacement = Items.MAGIC_ESSENCE_3, potionType = PotionType.MAGIC_ESSENCE),
    MAGIC_ESSENCE3(item = Items.MAGIC_ESSENCE_3, replacement = Items.MAGIC_ESSENCE_2, potionType = PotionType.MAGIC_ESSENCE),
    MAGIC_ESSENCE2(item = Items.MAGIC_ESSENCE_2, replacement = Items.MAGIC_ESSENCE_1, potionType = PotionType.MAGIC_ESSENCE),
    MAGIC_ESSENCE1(item = Items.MAGIC_ESSENCE_1, replacement = Items.VIAL, potionType = PotionType.MAGIC_ESSENCE),

    // OSRS-IMPORT potions-combat.
    SUPER_COMBAT4(item = Items.SUPER_COMBAT_POTION_4, replacement = Items.SUPER_COMBAT_POTION_3, potionType = PotionType.SUPER_COMBAT),
    SUPER_COMBAT3(item = Items.SUPER_COMBAT_POTION_3, replacement = Items.SUPER_COMBAT_POTION_2, potionType = PotionType.SUPER_COMBAT),
    SUPER_COMBAT2(item = Items.SUPER_COMBAT_POTION_2, replacement = Items.SUPER_COMBAT_POTION_1, potionType = PotionType.SUPER_COMBAT),
    SUPER_COMBAT1(item = Items.SUPER_COMBAT_POTION_1, replacement = Items.VIAL, potionType = PotionType.SUPER_COMBAT),
    DIVINE_SUPER_COMBAT4(item = Items.DIVINE_SUPER_COMBAT_POTION_4, replacement = Items.DIVINE_SUPER_COMBAT_POTION_3, potionType = PotionType.DIVINE_SUPER_COMBAT),
    DIVINE_SUPER_COMBAT3(item = Items.DIVINE_SUPER_COMBAT_POTION_3, replacement = Items.DIVINE_SUPER_COMBAT_POTION_2, potionType = PotionType.DIVINE_SUPER_COMBAT),
    DIVINE_SUPER_COMBAT2(item = Items.DIVINE_SUPER_COMBAT_POTION_2, replacement = Items.DIVINE_SUPER_COMBAT_POTION_1, potionType = PotionType.DIVINE_SUPER_COMBAT),
    DIVINE_SUPER_COMBAT1(item = Items.DIVINE_SUPER_COMBAT_POTION_1, replacement = Items.VIAL, potionType = PotionType.DIVINE_SUPER_COMBAT),
    DIVINE_SUPER_ATTACK4(item = Items.DIVINE_SUPER_ATTACK_POTION_4, replacement = Items.DIVINE_SUPER_ATTACK_POTION_3, potionType = PotionType.DIVINE_SUPER_ATTACK),
    DIVINE_SUPER_ATTACK3(item = Items.DIVINE_SUPER_ATTACK_POTION_3, replacement = Items.DIVINE_SUPER_ATTACK_POTION_2, potionType = PotionType.DIVINE_SUPER_ATTACK),
    DIVINE_SUPER_ATTACK2(item = Items.DIVINE_SUPER_ATTACK_POTION_2, replacement = Items.DIVINE_SUPER_ATTACK_POTION_1, potionType = PotionType.DIVINE_SUPER_ATTACK),
    DIVINE_SUPER_ATTACK1(item = Items.DIVINE_SUPER_ATTACK_POTION_1, replacement = Items.VIAL, potionType = PotionType.DIVINE_SUPER_ATTACK),
    DIVINE_SUPER_STRENGTH4(item = Items.DIVINE_SUPER_STRENGTH_POTION_4, replacement = Items.DIVINE_SUPER_STRENGTH_POTION_3, potionType = PotionType.DIVINE_SUPER_STRENGTH),
    DIVINE_SUPER_STRENGTH3(item = Items.DIVINE_SUPER_STRENGTH_POTION_3, replacement = Items.DIVINE_SUPER_STRENGTH_POTION_2, potionType = PotionType.DIVINE_SUPER_STRENGTH),
    DIVINE_SUPER_STRENGTH2(item = Items.DIVINE_SUPER_STRENGTH_POTION_2, replacement = Items.DIVINE_SUPER_STRENGTH_POTION_1, potionType = PotionType.DIVINE_SUPER_STRENGTH),
    DIVINE_SUPER_STRENGTH1(item = Items.DIVINE_SUPER_STRENGTH_POTION_1, replacement = Items.VIAL, potionType = PotionType.DIVINE_SUPER_STRENGTH),
    DIVINE_SUPER_DEFENCE4(item = Items.DIVINE_SUPER_DEFENCE_POTION_4, replacement = Items.DIVINE_SUPER_DEFENCE_POTION_3, potionType = PotionType.DIVINE_SUPER_DEFENCE),
    DIVINE_SUPER_DEFENCE3(item = Items.DIVINE_SUPER_DEFENCE_POTION_3, replacement = Items.DIVINE_SUPER_DEFENCE_POTION_2, potionType = PotionType.DIVINE_SUPER_DEFENCE),
    DIVINE_SUPER_DEFENCE2(item = Items.DIVINE_SUPER_DEFENCE_POTION_2, replacement = Items.DIVINE_SUPER_DEFENCE_POTION_1, potionType = PotionType.DIVINE_SUPER_DEFENCE),
    DIVINE_SUPER_DEFENCE1(item = Items.DIVINE_SUPER_DEFENCE_POTION_1, replacement = Items.VIAL, potionType = PotionType.DIVINE_SUPER_DEFENCE),
    DIVINE_RANGING4(item = Items.DIVINE_RANGING_POTION_4, replacement = Items.DIVINE_RANGING_POTION_3, potionType = PotionType.DIVINE_RANGING),
    DIVINE_RANGING3(item = Items.DIVINE_RANGING_POTION_3, replacement = Items.DIVINE_RANGING_POTION_2, potionType = PotionType.DIVINE_RANGING),
    DIVINE_RANGING2(item = Items.DIVINE_RANGING_POTION_2, replacement = Items.DIVINE_RANGING_POTION_1, potionType = PotionType.DIVINE_RANGING),
    DIVINE_RANGING1(item = Items.DIVINE_RANGING_POTION_1, replacement = Items.VIAL, potionType = PotionType.DIVINE_RANGING),
    DIVINE_MAGIC4(item = Items.DIVINE_MAGIC_POTION_4, replacement = Items.DIVINE_MAGIC_POTION_3, potionType = PotionType.DIVINE_MAGIC),
    DIVINE_MAGIC3(item = Items.DIVINE_MAGIC_POTION_3, replacement = Items.DIVINE_MAGIC_POTION_2, potionType = PotionType.DIVINE_MAGIC),
    DIVINE_MAGIC2(item = Items.DIVINE_MAGIC_POTION_2, replacement = Items.DIVINE_MAGIC_POTION_1, potionType = PotionType.DIVINE_MAGIC),
    DIVINE_MAGIC1(item = Items.DIVINE_MAGIC_POTION_1, replacement = Items.VIAL, potionType = PotionType.DIVINE_MAGIC),
    BATTLEMAGE4(item = Items.BATTLEMAGE_POTION_4, replacement = Items.BATTLEMAGE_POTION_3, potionType = PotionType.BATTLEMAGE),
    BATTLEMAGE3(item = Items.BATTLEMAGE_POTION_3, replacement = Items.BATTLEMAGE_POTION_2, potionType = PotionType.BATTLEMAGE),
    BATTLEMAGE2(item = Items.BATTLEMAGE_POTION_2, replacement = Items.BATTLEMAGE_POTION_1, potionType = PotionType.BATTLEMAGE),
    BATTLEMAGE1(item = Items.BATTLEMAGE_POTION_1, replacement = Items.VIAL, potionType = PotionType.BATTLEMAGE),
    BASTION4(item = Items.BASTION_POTION_4, replacement = Items.BASTION_POTION_3, potionType = PotionType.BASTION),
    BASTION3(item = Items.BASTION_POTION_3, replacement = Items.BASTION_POTION_2, potionType = PotionType.BASTION),
    BASTION2(item = Items.BASTION_POTION_2, replacement = Items.BASTION_POTION_1, potionType = PotionType.BASTION),
    BASTION1(item = Items.BASTION_POTION_1, replacement = Items.VIAL, potionType = PotionType.BASTION),
    DIVINE_BATTLEMAGE4(item = Items.DIVINE_BATTLEMAGE_POTION_4, replacement = Items.DIVINE_BATTLEMAGE_POTION_3, potionType = PotionType.DIVINE_BATTLEMAGE),
    DIVINE_BATTLEMAGE3(item = Items.DIVINE_BATTLEMAGE_POTION_3, replacement = Items.DIVINE_BATTLEMAGE_POTION_2, potionType = PotionType.DIVINE_BATTLEMAGE),
    DIVINE_BATTLEMAGE2(item = Items.DIVINE_BATTLEMAGE_POTION_2, replacement = Items.DIVINE_BATTLEMAGE_POTION_1, potionType = PotionType.DIVINE_BATTLEMAGE),
    DIVINE_BATTLEMAGE1(item = Items.DIVINE_BATTLEMAGE_POTION_1, replacement = Items.VIAL, potionType = PotionType.DIVINE_BATTLEMAGE),
    DIVINE_BASTION4(item = Items.DIVINE_BASTION_POTION_4, replacement = Items.DIVINE_BASTION_POTION_3, potionType = PotionType.DIVINE_BASTION),
    DIVINE_BASTION3(item = Items.DIVINE_BASTION_POTION_3, replacement = Items.DIVINE_BASTION_POTION_2, potionType = PotionType.DIVINE_BASTION),
    DIVINE_BASTION2(item = Items.DIVINE_BASTION_POTION_2, replacement = Items.DIVINE_BASTION_POTION_1, potionType = PotionType.DIVINE_BASTION),
    DIVINE_BASTION1(item = Items.DIVINE_BASTION_POTION_1, replacement = Items.VIAL, potionType = PotionType.DIVINE_BASTION),

    // OSRS-IMPORT potions-venom.
    ANTI_VENOM4(item = Items.ANTI_VENOM_4, replacement = Items.ANTI_VENOM_3, potionType = PotionType.ANTI_VENOM),
    ANTI_VENOM3(item = Items.ANTI_VENOM_3, replacement = Items.ANTI_VENOM_2, potionType = PotionType.ANTI_VENOM),
    ANTI_VENOM2(item = Items.ANTI_VENOM_2, replacement = Items.ANTI_VENOM_1, potionType = PotionType.ANTI_VENOM),
    ANTI_VENOM1(item = Items.ANTI_VENOM_1, replacement = Items.VIAL, potionType = PotionType.ANTI_VENOM),
    ANTI_VENOM_PLUS4(item = Items.ANTI_VENOM_PLUS_4, replacement = Items.ANTI_VENOM_PLUS_3, potionType = PotionType.ANTI_VENOM_PLUS),
    ANTI_VENOM_PLUS3(item = Items.ANTI_VENOM_PLUS_3, replacement = Items.ANTI_VENOM_PLUS_2, potionType = PotionType.ANTI_VENOM_PLUS),
    ANTI_VENOM_PLUS2(item = Items.ANTI_VENOM_PLUS_2, replacement = Items.ANTI_VENOM_PLUS_1, potionType = PotionType.ANTI_VENOM_PLUS),
    ANTI_VENOM_PLUS1(item = Items.ANTI_VENOM_PLUS_1, replacement = Items.VIAL, potionType = PotionType.ANTI_VENOM_PLUS),
    EXTENDED_ANTI_VENOM_PLUS4(item = Items.EXTENDED_ANTI_VENOM_PLUS_4, replacement = Items.EXTENDED_ANTI_VENOM_PLUS_3, potionType = PotionType.EXTENDED_ANTI_VENOM_PLUS),
    EXTENDED_ANTI_VENOM_PLUS3(item = Items.EXTENDED_ANTI_VENOM_PLUS_3, replacement = Items.EXTENDED_ANTI_VENOM_PLUS_2, potionType = PotionType.EXTENDED_ANTI_VENOM_PLUS),
    EXTENDED_ANTI_VENOM_PLUS2(item = Items.EXTENDED_ANTI_VENOM_PLUS_2, replacement = Items.EXTENDED_ANTI_VENOM_PLUS_1, potionType = PotionType.EXTENDED_ANTI_VENOM_PLUS),
    EXTENDED_ANTI_VENOM_PLUS1(item = Items.EXTENDED_ANTI_VENOM_PLUS_1, replacement = Items.VIAL, potionType = PotionType.EXTENDED_ANTI_VENOM_PLUS),

    // OSRS-IMPORT potions-stamina.
    STAMINA4(item = Items.STAMINA_POTION_4, replacement = Items.STAMINA_POTION_3, potionType = PotionType.STAMINA),
    STAMINA3(item = Items.STAMINA_POTION_3, replacement = Items.STAMINA_POTION_2, potionType = PotionType.STAMINA),
    STAMINA2(item = Items.STAMINA_POTION_2, replacement = Items.STAMINA_POTION_1, potionType = PotionType.STAMINA),
    STAMINA1(item = Items.STAMINA_POTION_1, replacement = Items.VIAL, potionType = PotionType.STAMINA),
    STAMINA_MIX2(item = Items.STAMINA_MIX_2, replacement = Items.STAMINA_MIX_1, potionType = PotionType.STAMINA_MIX),
    STAMINA_MIX1(item = Items.STAMINA_MIX_1, replacement = Items.VIAL, potionType = PotionType.STAMINA_MIX),
    EXTENDED_STAMINA4(item = Items.EXTENDED_STAMINA_POTION_4, replacement = Items.EXTENDED_STAMINA_POTION_3, potionType = PotionType.EXTENDED_STAMINA),
    EXTENDED_STAMINA3(item = Items.EXTENDED_STAMINA_POTION_3, replacement = Items.EXTENDED_STAMINA_POTION_2, potionType = PotionType.EXTENDED_STAMINA),
    EXTENDED_STAMINA2(item = Items.EXTENDED_STAMINA_POTION_2, replacement = Items.EXTENDED_STAMINA_POTION_1, potionType = PotionType.EXTENDED_STAMINA),
    EXTENDED_STAMINA1(item = Items.EXTENDED_STAMINA_POTION_1, replacement = Items.VIAL, potionType = PotionType.EXTENDED_STAMINA),
    EXTREME_ENERGY4(item = Items.EXTREME_ENERGY_POTION_4, replacement = Items.EXTREME_ENERGY_POTION_3, potionType = PotionType.EXTREME_ENERGY),
    EXTREME_ENERGY3(item = Items.EXTREME_ENERGY_POTION_3, replacement = Items.EXTREME_ENERGY_POTION_2, potionType = PotionType.EXTREME_ENERGY),
    EXTREME_ENERGY2(item = Items.EXTREME_ENERGY_POTION_2, replacement = Items.EXTREME_ENERGY_POTION_1, potionType = PotionType.EXTREME_ENERGY),
    EXTREME_ENERGY1(item = Items.EXTREME_ENERGY_POTION_1, replacement = Items.VIAL, potionType = PotionType.EXTREME_ENERGY),

    // OSRS-IMPORT potions-brews.
    ANCIENT_BREW4(item = Items.ANCIENT_BREW_4, replacement = Items.ANCIENT_BREW_3, potionType = PotionType.ANCIENT_BREW),
    ANCIENT_BREW3(item = Items.ANCIENT_BREW_3, replacement = Items.ANCIENT_BREW_2, potionType = PotionType.ANCIENT_BREW),
    ANCIENT_BREW2(item = Items.ANCIENT_BREW_2, replacement = Items.ANCIENT_BREW_1, potionType = PotionType.ANCIENT_BREW),
    ANCIENT_BREW1(item = Items.ANCIENT_BREW_1, replacement = Items.VIAL, potionType = PotionType.ANCIENT_BREW),
    ANCIENT_MIX2(item = Items.ANCIENT_MIX_2, replacement = Items.ANCIENT_MIX_1, potionType = PotionType.ANCIENT_MIX),
    ANCIENT_MIX1(item = Items.ANCIENT_MIX_1, replacement = Items.VIAL, potionType = PotionType.ANCIENT_MIX),
    FORGOTTEN_BREW4(item = Items.FORGOTTEN_BREW_4, replacement = Items.FORGOTTEN_BREW_3, potionType = PotionType.FORGOTTEN_BREW),
    FORGOTTEN_BREW3(item = Items.FORGOTTEN_BREW_3, replacement = Items.FORGOTTEN_BREW_2, potionType = PotionType.FORGOTTEN_BREW),
    FORGOTTEN_BREW2(item = Items.FORGOTTEN_BREW_2, replacement = Items.FORGOTTEN_BREW_1, potionType = PotionType.FORGOTTEN_BREW),
    FORGOTTEN_BREW1(item = Items.FORGOTTEN_BREW_1, replacement = Items.VIAL, potionType = PotionType.FORGOTTEN_BREW),
    ARMADYL_BREW4(item = Items.ARMADYL_BREW_4, replacement = Items.ARMADYL_BREW_3, potionType = PotionType.ARMADYL_BREW),
    ARMADYL_BREW3(item = Items.ARMADYL_BREW_3, replacement = Items.ARMADYL_BREW_2, potionType = PotionType.ARMADYL_BREW),
    ARMADYL_BREW2(item = Items.ARMADYL_BREW_2, replacement = Items.ARMADYL_BREW_1, potionType = PotionType.ARMADYL_BREW),
    ARMADYL_BREW1(item = Items.ARMADYL_BREW_1, replacement = Items.VIAL, potionType = PotionType.ARMADYL_BREW),
    MENAPHITE_REMEDY4(item = Items.MENAPHITE_REMEDY_4, replacement = Items.MENAPHITE_REMEDY_3, potionType = PotionType.MENAPHITE_REMEDY),
    MENAPHITE_REMEDY3(item = Items.MENAPHITE_REMEDY_3, replacement = Items.MENAPHITE_REMEDY_2, potionType = PotionType.MENAPHITE_REMEDY),
    MENAPHITE_REMEDY2(item = Items.MENAPHITE_REMEDY_2, replacement = Items.MENAPHITE_REMEDY_1, potionType = PotionType.MENAPHITE_REMEDY),
    MENAPHITE_REMEDY1(item = Items.MENAPHITE_REMEDY_1, replacement = Items.VIAL, potionType = PotionType.MENAPHITE_REMEDY),
    PRAYER_REGENERATION4(item = Items.PRAYER_REGENERATION_POTION_4, replacement = Items.PRAYER_REGENERATION_POTION_3, potionType = PotionType.PRAYER_REGENERATION),
    PRAYER_REGENERATION3(item = Items.PRAYER_REGENERATION_POTION_3, replacement = Items.PRAYER_REGENERATION_POTION_2, potionType = PotionType.PRAYER_REGENERATION),
    PRAYER_REGENERATION2(item = Items.PRAYER_REGENERATION_POTION_2, replacement = Items.PRAYER_REGENERATION_POTION_1, potionType = PotionType.PRAYER_REGENERATION),
    PRAYER_REGENERATION1(item = Items.PRAYER_REGENERATION_POTION_1, replacement = Items.VIAL, potionType = PotionType.PRAYER_REGENERATION),
    SURGE4(item = Items.SURGE_POTION_4, replacement = Items.SURGE_POTION_3, potionType = PotionType.SURGE),
    SURGE3(item = Items.SURGE_POTION_3, replacement = Items.SURGE_POTION_2, potionType = PotionType.SURGE),
    SURGE2(item = Items.SURGE_POTION_2, replacement = Items.SURGE_POTION_1, potionType = PotionType.SURGE),
    SURGE1(item = Items.SURGE_POTION_1, replacement = Items.VIAL, potionType = PotionType.SURGE),
    GOADING4(item = Items.GOADING_POTION_4, replacement = Items.GOADING_POTION_3, potionType = PotionType.GOADING),
    GOADING3(item = Items.GOADING_POTION_3, replacement = Items.GOADING_POTION_2, potionType = PotionType.GOADING),
    GOADING2(item = Items.GOADING_POTION_2, replacement = Items.GOADING_POTION_1, potionType = PotionType.GOADING),
    GOADING1(item = Items.GOADING_POTION_1, replacement = Items.VIAL, potionType = PotionType.GOADING),

    // OSRS-IMPORT potions-skill.
    SUPER_FISHING4(item = Items.SUPER_FISHING_POTION_4, replacement = Items.SUPER_FISHING_POTION_3, potionType = PotionType.SUPER_FISHING),
    SUPER_FISHING3(item = Items.SUPER_FISHING_POTION_3, replacement = Items.SUPER_FISHING_POTION_2, potionType = PotionType.SUPER_FISHING),
    SUPER_FISHING2(item = Items.SUPER_FISHING_POTION_2, replacement = Items.SUPER_FISHING_POTION_1, potionType = PotionType.SUPER_FISHING),
    SUPER_FISHING1(item = Items.SUPER_FISHING_POTION_1, replacement = Items.VIAL, potionType = PotionType.SUPER_FISHING),
    SUPER_HUNTER4(item = Items.SUPER_HUNTER_POTION_4, replacement = Items.SUPER_HUNTER_POTION_3, potionType = PotionType.SUPER_HUNTER),
    SUPER_HUNTER3(item = Items.SUPER_HUNTER_POTION_3, replacement = Items.SUPER_HUNTER_POTION_2, potionType = PotionType.SUPER_HUNTER),
    SUPER_HUNTER2(item = Items.SUPER_HUNTER_POTION_2, replacement = Items.SUPER_HUNTER_POTION_1, potionType = PotionType.SUPER_HUNTER),
    SUPER_HUNTER1(item = Items.SUPER_HUNTER_POTION_1, replacement = Items.VIAL, potionType = PotionType.SUPER_HUNTER),
    RUBY_HARVEST_MIX2(item = Items.RUBY_HARVEST_MIX_2, replacement = Items.RUBY_HARVEST_MIX_1, potionType = PotionType.RUBY_HARVEST_MIX),
    RUBY_HARVEST_MIX1(item = Items.RUBY_HARVEST_MIX_1, replacement = Items.VIAL, potionType = PotionType.RUBY_HARVEST_MIX),
    SAPPHIRE_GLACIALIS_MIX2(item = Items.SAPPHIRE_GLACIALIS_MIX_2, replacement = Items.SAPPHIRE_GLACIALIS_MIX_1, potionType = PotionType.SAPPHIRE_GLACIALIS_MIX),
    SAPPHIRE_GLACIALIS_MIX1(item = Items.SAPPHIRE_GLACIALIS_MIX_1, replacement = Items.VIAL, potionType = PotionType.SAPPHIRE_GLACIALIS_MIX),
    BLACK_WARLOCK_MIX2(item = Items.BLACK_WARLOCK_MIX_2, replacement = Items.BLACK_WARLOCK_MIX_1, potionType = PotionType.BLACK_WARLOCK_MIX),
    BLACK_WARLOCK_MIX1(item = Items.BLACK_WARLOCK_MIX_1, replacement = Items.VIAL, potionType = PotionType.BLACK_WARLOCK_MIX),
    SNOWY_KNIGHT_MIX2(item = Items.SNOWY_KNIGHT_MIX_2, replacement = Items.SNOWY_KNIGHT_MIX_1, potionType = PotionType.SNOWY_KNIGHT_MIX),
    SNOWY_KNIGHT_MIX1(item = Items.SNOWY_KNIGHT_MIX_1, replacement = Items.VIAL, potionType = PotionType.SNOWY_KNIGHT_MIX),
    MOONLIGHT_MOTH_MIX2(item = Items.MOONLIGHT_MOTH_MIX_2, replacement = Items.MOONLIGHT_MOTH_MIX_1, potionType = PotionType.MOONLIGHT_MOTH_MIX),
    MOONLIGHT_MOTH_MIX1(item = Items.MOONLIGHT_MOTH_MIX_1, replacement = Items.VIAL, potionType = PotionType.MOONLIGHT_MOTH_MIX),
    SUNLIGHT_MOTH_MIX2(item = Items.SUNLIGHT_MOTH_MIX_2, replacement = Items.SUNLIGHT_MOTH_MIX_1, potionType = PotionType.SUNLIGHT_MOTH_MIX),
    SUNLIGHT_MOTH_MIX1(item = Items.SUNLIGHT_MOTH_MIX_1, replacement = Items.VIAL, potionType = PotionType.SUNLIGHT_MOTH_MIX),

    // OSRS-IMPORT step 4 batch potions-antifire (owner answer Q8).
    EXTENDED_ANTIFIRE4(item = Items.EXTENDED_ANTIFIRE_4, replacement = Items.EXTENDED_ANTIFIRE_3, potionType = PotionType.EXTENDED_ANTIFIRE),
    EXTENDED_ANTIFIRE3(item = Items.EXTENDED_ANTIFIRE_3, replacement = Items.EXTENDED_ANTIFIRE_2, potionType = PotionType.EXTENDED_ANTIFIRE),
    EXTENDED_ANTIFIRE2(item = Items.EXTENDED_ANTIFIRE_2, replacement = Items.EXTENDED_ANTIFIRE_1, potionType = PotionType.EXTENDED_ANTIFIRE),
    EXTENDED_ANTIFIRE1(item = Items.EXTENDED_ANTIFIRE_1, replacement = Items.VIAL, potionType = PotionType.EXTENDED_ANTIFIRE),
    EXTENDED_ANTIFIRE_MIX2(item = Items.EXTENDED_ANTIFIRE_MIX_2, replacement = Items.EXTENDED_ANTIFIRE_MIX_1, potionType = PotionType.EXTENDED_ANTIFIRE_MIX),
    EXTENDED_ANTIFIRE_MIX1(item = Items.EXTENDED_ANTIFIRE_MIX_1, replacement = Items.VIAL, potionType = PotionType.EXTENDED_ANTIFIRE_MIX),
    SUPER_ANTIFIRE_MIX2(item = Items.SUPER_ANTIFIRE_MIX_2, replacement = Items.SUPER_ANTIFIRE_MIX_1, potionType = PotionType.SUPER_ANTIFIRE_MIX),
    SUPER_ANTIFIRE_MIX1(item = Items.SUPER_ANTIFIRE_MIX_1, replacement = Items.VIAL, potionType = PotionType.SUPER_ANTIFIRE_MIX),
    EXTENDED_SUPER_ANTIFIRE4(item = Items.EXTENDED_SUPER_ANTIFIRE_4, replacement = Items.EXTENDED_SUPER_ANTIFIRE_3, potionType = PotionType.EXTENDED_SUPER_ANTIFIRE),
    EXTENDED_SUPER_ANTIFIRE3(item = Items.EXTENDED_SUPER_ANTIFIRE_3, replacement = Items.EXTENDED_SUPER_ANTIFIRE_2, potionType = PotionType.EXTENDED_SUPER_ANTIFIRE),
    EXTENDED_SUPER_ANTIFIRE2(item = Items.EXTENDED_SUPER_ANTIFIRE_2, replacement = Items.EXTENDED_SUPER_ANTIFIRE_1, potionType = PotionType.EXTENDED_SUPER_ANTIFIRE),
    EXTENDED_SUPER_ANTIFIRE1(item = Items.EXTENDED_SUPER_ANTIFIRE_1, replacement = Items.VIAL, potionType = PotionType.EXTENDED_SUPER_ANTIFIRE),
    EXTENDED_SUPER_ANTIFIRE_MIX2(item = Items.EXTENDED_SUPER_ANTIFIRE_MIX_2, replacement = Items.EXTENDED_SUPER_ANTIFIRE_MIX_1, potionType = PotionType.EXTENDED_SUPER_ANTIFIRE_MIX),
    EXTENDED_SUPER_ANTIFIRE_MIX1(item = Items.EXTENDED_SUPER_ANTIFIRE_MIX_1, replacement = Items.VIAL, potionType = PotionType.EXTENDED_SUPER_ANTIFIRE_MIX),

    // Adjacent gap: the 667 barbarian mixes had recipes but could not be drunk (OSRS Wiki Barbarian Training "Heals" table, BarbarianMixes).
    ATTACK_MIX2(item = Items.ATTACK_MIX_2, replacement = Items.ATTACK_MIX_1, potionType = PotionType.ATTACK, mixHeal = 3),
    ATTACK_MIX1(item = Items.ATTACK_MIX_1, replacement = Items.VIAL, potionType = PotionType.ATTACK, mixHeal = 3),
    ANTIPOISON_MIX2(item = Items.ANTIPOISON_MIX_2, replacement = Items.ANTIPOISON_MIX_1, potionType = PotionType.ANTIPOISON, mixHeal = 3),
    ANTIPOISON_MIX1(item = Items.ANTIPOISON_MIX_1, replacement = Items.VIAL, potionType = PotionType.ANTIPOISON, mixHeal = 3),
    STRENGTH_MIX2(item = Items.STRENGTH_MIX_2, replacement = Items.STRENGTH_MIX_1, potionType = PotionType.STRENGTH, mixHeal = 3),
    STRENGTH_MIX1(item = Items.STRENGTH_MIX_1, replacement = Items.VIAL, potionType = PotionType.STRENGTH, mixHeal = 3),
    RESTORE_MIX2(item = Items.RESTORE_MIX_2, replacement = Items.RESTORE_MIX_1, potionType = PotionType.RESTORE, mixHeal = 3),
    RESTORE_MIX1(item = Items.RESTORE_MIX_1, replacement = Items.VIAL, potionType = PotionType.RESTORE, mixHeal = 3),
    ENERGY_MIX2(item = Items.ENERGY_MIX_2, replacement = Items.ENERGY_MIX_1, potionType = PotionType.ENERGY, mixHeal = 3),
    ENERGY_MIX1(item = Items.ENERGY_MIX_1, replacement = Items.VIAL, potionType = PotionType.ENERGY, mixHeal = 3),
    DEFENCE_MIX2(item = Items.DEFENCE_MIX_2, replacement = Items.DEFENCE_MIX_1, potionType = PotionType.DEFENCE, mixHeal = 6),
    DEFENCE_MIX1(item = Items.DEFENCE_MIX_1, replacement = Items.VIAL, potionType = PotionType.DEFENCE, mixHeal = 6),
    AGILITY_MIX2(item = Items.AGILITY_MIX_2, replacement = Items.AGILITY_MIX_1, potionType = PotionType.AGILITY, mixHeal = 6),
    AGILITY_MIX1(item = Items.AGILITY_MIX_1, replacement = Items.VIAL, potionType = PotionType.AGILITY, mixHeal = 6),
    COMBAT_MIX2(item = Items.COMBAT_MIX_2, replacement = Items.COMBAT_MIX_1, potionType = PotionType.COMBAT, mixHeal = 3),
    COMBAT_MIX1(item = Items.COMBAT_MIX_1, replacement = Items.VIAL, potionType = PotionType.COMBAT, mixHeal = 3),
    PRAYER_MIX2(item = Items.PRAYER_MIX_2, replacement = Items.PRAYER_MIX_1, potionType = PotionType.PRAYER, mixHeal = 6),
    PRAYER_MIX1(item = Items.PRAYER_MIX_1, replacement = Items.VIAL, potionType = PotionType.PRAYER, mixHeal = 6),
    SUPER_ATTACK_MIX2(item = Items.SUPER_ATTACK_MIX_2, replacement = Items.SUPER_ATTACK_MIX_1, potionType = PotionType.SUPER_ATTACK, mixHeal = 6),
    SUPER_ATTACK_MIX1(item = Items.SUPER_ATTACK_MIX_1, replacement = Items.VIAL, potionType = PotionType.SUPER_ATTACK, mixHeal = 6),
    ANTIP_SUPERMIX2(item = Items.ANTIP_SUPERMIX_2, replacement = Items.ANTIP_SUPERMIX_1, potionType = PotionType.SUPER_ANTIPOISON, mixHeal = 6),
    ANTIP_SUPERMIX1(item = Items.ANTIP_SUPERMIX_1, replacement = Items.VIAL, potionType = PotionType.SUPER_ANTIPOISON, mixHeal = 6),
    FISHING_MIX2(item = Items.FISHING_MIX_2, replacement = Items.FISHING_MIX_1, potionType = PotionType.FISHING, mixHeal = 6),
    FISHING_MIX1(item = Items.FISHING_MIX_1, replacement = Items.VIAL, potionType = PotionType.FISHING, mixHeal = 6),
    SUPER_ENERGY_MIX2(item = Items.SUPER_ENERGY_MIX_2, replacement = Items.SUPER_ENERGY_MIX_1, potionType = PotionType.SUPER_ENERGY, mixHeal = 6),
    SUPER_ENERGY_MIX1(item = Items.SUPER_ENERGY_MIX_1, replacement = Items.VIAL, potionType = PotionType.SUPER_ENERGY, mixHeal = 6),
    HUNTING_MIX2(item = Items.HUNTING_MIX_2, replacement = Items.HUNTING_MIX_1, potionType = PotionType.HUNTER, mixHeal = 6),
    HUNTING_MIX1(item = Items.HUNTING_MIX_1, replacement = Items.VIAL, potionType = PotionType.HUNTER, mixHeal = 6),
    SUPER_STRENGTH_MIX2(item = Items.SUPER_STRENGTH_MIX_2, replacement = Items.SUPER_STRENGTH_MIX_1, potionType = PotionType.SUPER_STRENGTH, mixHeal = 6),
    SUPER_STRENGTH_MIX1(item = Items.SUPER_STRENGTH_MIX_1, replacement = Items.VIAL, potionType = PotionType.SUPER_STRENGTH, mixHeal = 6),
    MAGIC_ESSENCE_MIX2(item = Items.MAGIC_ESSENCE_MIX_2, replacement = Items.MAGIC_ESSENCE_MIX_1, potionType = PotionType.MAGIC_ESSENCE, mixHeal = 6),
    MAGIC_ESSENCE_MIX1(item = Items.MAGIC_ESSENCE_MIX_1, replacement = Items.VIAL, potionType = PotionType.MAGIC_ESSENCE, mixHeal = 6),
    SUPER_RESTORE_MIX2(item = Items.SUPER_RESTORE_MIX_2, replacement = Items.SUPER_RESTORE_MIX_1, potionType = PotionType.SUPER_RESTORE, mixHeal = 6),
    SUPER_RESTORE_MIX1(item = Items.SUPER_RESTORE_MIX_1, replacement = Items.VIAL, potionType = PotionType.SUPER_RESTORE, mixHeal = 6),
    SUPER_DEFENCE_MIX2(item = Items.SUPER_DEFENCE_MIX_2, replacement = Items.SUPER_DEFENCE_MIX_1, potionType = PotionType.SUPER_DEFENCE, mixHeal = 6),
    SUPER_DEFENCE_MIX1(item = Items.SUPER_DEFENCE_MIX_1, replacement = Items.VIAL, potionType = PotionType.SUPER_DEFENCE, mixHeal = 6),
    ANTIDOTE_MIX2(item = Items.ANTIDOTE_MIX_2, replacement = Items.ANTIDOTE_MIX_1, potionType = PotionType.ANTIPOISON_PLUS, mixHeal = 6),
    ANTIDOTE_MIX1(item = Items.ANTIDOTE_MIX_1, replacement = Items.VIAL, potionType = PotionType.ANTIPOISON_PLUS, mixHeal = 6),
    ANTIFIRE_MIX2(item = Items.ANTIFIRE_MIX_2, replacement = Items.ANTIFIRE_MIX_1, potionType = PotionType.ANTIFIRE, mixHeal = 6),
    ANTIFIRE_MIX1(item = Items.ANTIFIRE_MIX_1, replacement = Items.VIAL, potionType = PotionType.ANTIFIRE, mixHeal = 6),
    RANGING_MIX2(item = Items.RANGING_MIX_2, replacement = Items.RANGING_MIX_1, potionType = PotionType.RANGING, mixHeal = 6),
    RANGING_MIX1(item = Items.RANGING_MIX_1, replacement = Items.VIAL, potionType = PotionType.RANGING, mixHeal = 6),
    MAGIC_MIX2(item = Items.MAGIC_MIX_2, replacement = Items.MAGIC_MIX_1, potionType = PotionType.MAGIC, mixHeal = 6),
    MAGIC_MIX1(item = Items.MAGIC_MIX_1, replacement = Items.VIAL, potionType = PotionType.MAGIC, mixHeal = 6),
    ZAMORAK_MIX2(item = Items.ZAMORAK_MIX_2, replacement = Items.ZAMORAK_MIX_1, potionType = PotionType.ZAMORAK_BREW, mixHeal = 6),
    ZAMORAK_MIX1(item = Items.ZAMORAK_MIX_1, replacement = Items.VIAL, potionType = PotionType.ZAMORAK_BREW, mixHeal = 6),
}
