package gg.rsmod.game.tools.importer

import com.displee.cache.CacheLibrary

/**
 * Read-only, offline decoder for interface component hook bindings and CS2 client
 * scripts. Ported directly (byte-for-byte, same field order and same optional-field
 * conditions) from the real deobfuscated client decode logic in `2011scape-client`:
 * `Component.decode()` / `Component.decodeComponentHook()` / `Component.decodeTransmitList()`
 * for interface components, and `ClientScript.decode()` for CS2 scripts.
 *
 * Purpose: find which CS2 script id(s) an interface component's onVarTransmit /
 * onInvTransmit / onClick / etc hooks are bound to, and decode that script's raw
 * opcode stream - without needing a live client runtime trace. The hooks are baked
 * statically into the interface archive at build time (they are the compiled output
 * of `cc_if_setonvartransmit`-style calls), so they are fully and deterministically
 * recoverable from cache bytes alone.
 *
 * Archive numbering matches the client's own `com.jagex.js5.js5` registry:
 * archive 3 = interfaces (group = interface id, file = component slot),
 * archive 12 = clientscripts (group = script id, file = 0).
 *
 * Usage:
 *   Interface mode: `./gradlew :game:runInterfaceHookProbeTool --args="<cachePath> interface <interfaceId> [slot ...]"`
 *     (with no slots given, every component in the interface is scanned but only
 *     components with at least one hook/trigger set are printed)
 *   Layout mode:    `./gradlew :game:runInterfaceHookProbeTool --args="<cachePath> layout <interfaceId> [slot ...]"`
 *     prints the click-relevant structure of every component: type, parent layer,
 *     clientcode, opBase, the ops[] strings, and the baked `events` bitmask decoded
 *     into the ops it enables. This is what tells you which component id an action
 *     actually lives on and which op index (and therefore which IF_BUTTONn opcode)
 *     the server must enable via IfSetEvents before the client will offer it at all.
 *   Script mode:    `./gradlew :game:runInterfaceHookProbeTool --args="<cachePath> script <scriptId> [scriptId ...]"`
 *   Disasm mode:    `./gradlew :game:runInterfaceHookProbeTool --args="<cachePath> disasm <scriptId> [scriptId ...]"`
 *     Same decode as script mode, but each opcode is annotated with its real mnemonic from
 *     `com.jagex.core.constants.ClientScriptOpCode` (loaded from `cs2/opcodes.txt`, generated by
 *     grepping every `public static final int NAME = number;` out of that class - the client's own
 *     opcode table, not a guess). Operands that are themselves opcode-like small ints are left as
 *     plain numbers; only the opcode column is annotated.
 *   Search mode:    `./gradlew :game:runInterfaceHookProbeTool --args="<cachePath> search <text>"`
 *     scans every component of every interface for a case-insensitive substring of its name,
 *     static text, op base or op labels - the only offline way to locate an interface by its
 *     user-visible wording, since the cache carries no interface-name table.
 *   Reference mode: `./gradlew :game:runInterfaceHookProbeTool --args="<cachePath> compref <interfaceId> <componentId>"`
 */
object InterfaceHookProbeTool {
    private const val ARCHIVE_INTERFACES = 3
    private const val ARCHIVE_CLIENTSCRIPTS = 12

    @JvmStatic
    fun main(args: Array<String>) {
        require(args.size >= 3) {
            "Usage: <cachePath> interface|layout <interfaceId> [slot ...] | <cachePath> script <scriptId> [scriptId ...]"
        }
        val cachePath = args[0]
        val mode = args[1].lowercase()
        val library = CacheLibrary(cachePath)
        try {
            when (mode) {
                "interface" -> probeInterface(library, args[2].toInt(), args.drop(3).map { it.toInt() })
                "layout" -> probeLayout(library, args[2].toInt(), args.drop(3).map { it.toInt() })
                "script" -> args.drop(2).map { it.toInt() }.forEach { probeScript(library, it) }
                "disasm" -> args.drop(2).map { it.toInt() }.forEach { disasmScript(library, it) }
                "refs" -> probeRefs(library, args.drop(2).map { it.toInt() })
                "compref" -> probeRefs(library, listOf((args[2].toInt() shl 16) or args[3].toInt()))
                "search" -> probeSearch(library, args.drop(2).joinToString(" "))
                "strsearch" -> probeScriptStrings(library, args.drop(2).joinToString(" "))
                else -> error(
                    "Unknown mode '$mode', expected 'interface', 'layout', 'script', 'disasm', 'search', " +
                        "'strsearch', 'refs' or 'compref'",
                )
            }
        } finally {
            library.close()
        }
    }

    private fun probeInterface(
        library: CacheLibrary,
        interfaceId: Int,
        onlySlots: List<Int>,
    ) {
        println("INTERFACE=$interfaceId")
        val index = library.index(ARCHIVE_INTERFACES)
        val archive = index.archive(interfaceId)
        if (archive == null) {
            println(" ABSENT")
            return
        }
        val allSlots = archive.fileIds().sorted()
        println(" COMPONENT_COUNT=${allSlots.size}")
        val slots = onlySlots.ifEmpty { allSlots }
        for (slot in slots) {
            val bytes = library.data(ARCHIVE_INTERFACES, interfaceId, slot) ?: continue
            val c =
                try {
                    decodeComponent(bytes)
                } catch (e: Exception) {
                    println(" COMPONENT_$slot DECODE_ERROR=${e.message}")
                    continue
                }
            val hooks = c.hooks.filterValues { it != null }
            val triggers = c.triggers.filterValues { it != null }
            if (hooks.isEmpty() && triggers.isEmpty() && onlySlots.isEmpty()) continue
            println(" COMPONENT_$slot type=${c.type} name=${c.name}")
            hooks.forEach { (hookName, hookArgs) -> println("   $hookName=$hookArgs") }
            triggers.forEach { (triggerName, ids) -> println("   $triggerName=${ids?.toList()}") }
        }
    }

    /**
     * The click-relevant structure of an interface. `events` is the bitmask baked into the
     * cache; the server's own IfSetEvents overwrites it wholesale at runtime (see
     * ServerConnectionReader's IF_SETEVENTS branch), so a baked value of 0 means the
     * component is inert until the server enables it. Op index i is delivered to the server
     * as IF_BUTTON(i+1), whose ClientProt opcodes are 61,64,4,52,81,91,18,10,20,25 for
     * ops 1..10 respectively.
     */
    private fun probeLayout(
        library: CacheLibrary,
        interfaceId: Int,
        onlySlots: List<Int>,
    ) {
        println("INTERFACE=$interfaceId")
        val index = library.index(ARCHIVE_INTERFACES)
        val archive = index.archive(interfaceId)
        if (archive == null) {
            println(" ABSENT")
            return
        }
        val allSlots = archive.fileIds().sorted()
        println(" COMPONENT_COUNT=${allSlots.size}")
        for (slot in onlySlots.ifEmpty { allSlots }) {
            val bytes = library.data(ARCHIVE_INTERFACES, interfaceId, slot) ?: continue
            val c =
                try {
                    decodeComponent(bytes)
                } catch (e: Exception) {
                    println(" COMPONENT_$slot DECODE_ERROR=${e.message}")
                    continue
                }
            val parts = mutableListOf<String>()
            parts += "type=${typeName(c.type)}"
            parts += "box=${c.x},${c.y} ${c.width}x${c.height}"
            if (c.name != null) parts += "name=${c.name}"
            if (c.layer != -1) parts += "parent=${c.layer}"
            if (c.clientcode != 0) parts += "clientcode=${c.clientcode}"
            if (c.spriteId != -1) parts += "sprite=${c.spriteId}"
            if (c.modelId != -1) parts += "model=${c.modelId}"
            if (c.opBase.isNotEmpty()) parts += "opBase='${c.opBase}'"
            if (c.ops.isNotEmpty()) {
                parts += "ops=[" + c.ops.mapIndexed { i, op -> "${i + 1}:'${op ?: ""}'" }.joinToString(",") + "]"
            }
            parts += "events=0x%06x".format(c.events)
            val enabled = (0..9).filter { (c.events shr (it + 1)) and 0x1 != 0 }
            if (enabled.isNotEmpty()) {
                parts += "bakedOps=[" + enabled.joinToString(",") { "op${it + 1}=IF_BUTTON${it + 1}(${IF_BUTTON_OPCODES[it]})" } + "]"
            }
            if (c.events and 0x1 != 0) parts += "pauseButton"
            val targetMask = (c.events shr 11) and 0x7F
            if (targetMask != 0) parts += "targetMask=$targetMask"
            if (c.hooks.values.any { it != null }) {
                parts += "hooks=[" + c.hooks.filterValues { it != null }.keys.joinToString(",") + "]"
            }
            println(" COMPONENT_$slot " + parts.joinToString(" "))
        }
    }

    /**
     * Scans every interface in the cache for components whose name, static text, op base or
     * op labels contain [needle] (case-insensitive). This is the "which interface id is the
     * Price Checker / Notes / Adventurer's Log?" question - the cache has no interface-name
     * table, so the only reliable offline handle on an unknown interface is its own baked
     * user-visible strings.
     */
    private fun probeSearch(
        library: CacheLibrary,
        needle: String,
    ) {
        println("SEARCHING_FOR='$needle'")
        val index = library.index(ARCHIVE_INTERFACES)
        var scanned = 0
        var failed = 0
        var hits = 0
        for (interfaceId in index.archiveIds()) {
            val archive = index.archive(interfaceId) ?: continue
            for (slot in archive.fileIds().sorted()) {
                val bytes = library.data(ARCHIVE_INTERFACES, interfaceId, slot) ?: continue
                val c =
                    try {
                        scanned++
                        decodeComponent(bytes)
                    } catch (e: Exception) {
                        failed++
                        continue
                    }
                val fields = mutableListOf<String>()
                if (c.name?.contains(needle, ignoreCase = true) == true) fields += "name='${c.name}'"
                if (c.text?.contains(needle, ignoreCase = true) == true) fields += "text='${c.text}'"
                if (c.opBase.contains(needle, ignoreCase = true)) fields += "opBase='${c.opBase}'"
                c.ops.forEachIndexed { i, op ->
                    if (op?.contains(needle, ignoreCase = true) == true) fields += "op${i + 1}='$op'"
                }
                if (fields.isNotEmpty()) {
                    hits++
                    println("$interfaceId:$slot type=${typeName(c.type)} " + fields.joinToString(" "))
                }
            }
        }
        println("SCANNED=$scanned DECODE_FAILED=$failed HITS=$hits")
    }

    /**
     * Scans every CS2 script in the cache for the given int operands and reports which
     * scripts push them. Component hashes are `(interfaceId shl 16) or componentId`, so
     * `compref <interfaceId> <componentId>` answers "which client script builds/drives this
     * component?" - the question that decides whether a component's ops are baked into the
     * interface archive or created dynamically (and therefore need IfSetEvents from us).
     */
    /**
     * Finds every clientscript carrying a string constant that contains [needle]. Interface text is
     * searchable with `search`, but a great deal of user-visible wording is assembled at runtime by
     * cs2 (the follower panel's "Level 52: <name> (<n> Special Move points)" line, for instance)
     * and only exists as a script string operand, which no other mode can reach.
     */
    private fun probeScriptStrings(
        library: CacheLibrary,
        needle: String,
    ) {
        println("SEARCHING_SCRIPT_STRINGS_FOR='$needle'")
        val index = library.index(ARCHIVE_CLIENTSCRIPTS)
        var scanned = 0
        var failed = 0
        for (scriptId in index.archiveIds()) {
            val bytes = library.data(ARCHIVE_CLIENTSCRIPTS, scriptId, 0) ?: continue
            val script =
                try {
                    scanned++
                    decodeScript(bytes)
                } catch (e: Exception) {
                    failed++
                    continue
                }
            val strings = script.stringOperands ?: continue
            val hits = strings.indices.filter { strings[it]?.contains(needle, ignoreCase = true) == true }
            if (hits.isNotEmpty()) {
                println("SCRIPT_$scriptId hits=${hits.map { "[$it]='${strings[it]}'" }}")
            }
        }
        println("SCANNED=$scanned DECODE_FAILED=$failed")
    }

    private fun probeRefs(
        library: CacheLibrary,
        needles: List<Int>,
    ) {
        val needleSet = needles.toSet()
        needles.forEach { println("SEARCHING_FOR=$it (${it shr 16}:${it and 0xFFFF})") }
        val index = library.index(ARCHIVE_CLIENTSCRIPTS)
        var scanned = 0
        var failed = 0
        for (scriptId in index.archiveIds()) {
            val bytes = library.data(ARCHIVE_CLIENTSCRIPTS, scriptId, 0) ?: continue
            val script =
                try {
                    scanned++
                    decodeScript(bytes)
                } catch (e: Exception) {
                    failed++
                    continue
                }
            val operands = script.intOperands ?: continue
            val hits =
                operands.indices.filter {
                    operands[it] in needleSet &&
                        (script.opcodes[it] == PUSH_CONSTANT_INT || script.opcodes[it] == GOSUB_WITH_PARAMS || script.opcodes[it] in VAR_OPCODES)
                }
            if (hits.isNotEmpty()) {
                println("SCRIPT_$scriptId hits=${hits.map { "[$it]=${operands[it]}(op${script.opcodes[it]})" }}")
            }
        }
        println("SCANNED=$scanned DECODE_FAILED=$failed")
    }

    /** CS2 `push_constant_int`. */
    private const val PUSH_CONSTANT_INT = 0

    /**
     * CS2 `gosub_with_params`. Its operand is the *called script id*, so including it here turns
     * `refs <scriptId>` into a caller search - the only practical way to find what actually
     * invokes a helper script like the gameframe rebuild (1364), which no interface hook names
     * directly.
     */
    private const val GOSUB_WITH_PARAMS = 40

    /** CS2 push/pop varp (1,2), varbit (25,27) and varc (42,43) - their operands are variable ids, so `refs` matches them too. */
    private val VAR_OPCODES = setOf(1, 2, 25, 27, 42, 43)

    /** ClientProt opcode carried by IF_BUTTON1..IF_BUTTON10, indexed by op-1. */
    private val IF_BUTTON_OPCODES = intArrayOf(61, 64, 4, 52, 81, 91, 18, 10, 20, 25)

    private fun typeName(type: Int): String =
        when (type) {
            TYPE_LAYER -> "LAYER(0)"
            TYPE_RECTANGLE -> "RECTANGLE(3)"
            TYPE_TEXT -> "TEXT(4)"
            TYPE_GRAPHIC -> "GRAPHIC(5)"
            TYPE_MODEL -> "MODEL(6)"
            TYPE_LINE -> "LINE(9)"
            else -> "UNKNOWN($type)"
        }

    /**
     * `opcode -> mnemonic` table for CS2 client scripts, loaded from `cs2/opcodes.txt`
     * (`resource:number=NAME`, one per line). That file was generated once, mechanically, from
     * every `public static final int NAME = number;` in the real deobfuscated client's
     * `com.jagex.core.constants.ClientScriptOpCode` - it is the client's own opcode table, not a
     * reconstruction. A handful of numbers carry two names (e.g. 2614 is both `CC_GETMODEL` and
     * `IF_GETMODEL` - the same instruction addressed through the component or interface op family);
     * both are kept, joined with `/`.
     */
    private val CS2_MNEMONICS: Map<Int, String> by lazy {
        val merged = linkedMapOf<Int, MutableList<String>>()
        InterfaceHookProbeTool::class.java.classLoader
            .getResourceAsStream("cs2/opcodes.txt")
            ?.bufferedReader(Charsets.UTF_8)
            ?.useLines { lines ->
                lines.forEach { line ->
                    if (line.isBlank()) return@forEach
                    val (numStr, name) = line.split("=", limit = 2)
                    merged.getOrPut(numStr.trim().toInt()) { mutableListOf() }.add(name.trim())
                }
            }
        merged.mapValues { (_, names) -> names.distinct().joinToString("/") }
    }

    private fun mnemonic(opcode: Int): String = CS2_MNEMONICS[opcode] ?: "OP_$opcode"

    private fun disasmScript(
        library: CacheLibrary,
        scriptId: Int,
    ) {
        val bytes = library.data(ARCHIVE_CLIENTSCRIPTS, scriptId, 0)
        if (bytes == null) {
            println("SCRIPT_$scriptId=ABSENT")
            return
        }
        val script = decodeScript(bytes)
        println(
            "SCRIPT_$scriptId name=${script.name} opcodeCount=${script.opcodes.size} " +
                "intVarCount=${script.intVarCount} intArgCount=${script.intArgCount}",
        )
        val switchTargets = script.switchTables.flatMap { it.values }.toSet()
        for (idx in script.opcodes.indices) {
            val opcode = script.opcodes[idx]
            val mnem = mnemonic(opcode)
            val operand: Any? =
                when {
                    opcode == 3 -> script.stringOperands?.get(idx)?.let { "\"$it\"" }
                    else -> script.intOperands?.get(idx)
                }
            val marker = if (idx in switchTargets) " <-- switch target" else ""
            println(" [$idx] $mnem${if (operand != null) "($operand)" else ""}$marker")
        }
        script.switchTables.forEachIndexed { i, table -> println(" SWITCH_TABLE_$i=$table") }
    }

    private fun probeScript(
        library: CacheLibrary,
        scriptId: Int,
    ) {
        val bytes = library.data(ARCHIVE_CLIENTSCRIPTS, scriptId, 0)
        if (bytes == null) {
            println("SCRIPT_$scriptId=ABSENT")
            return
        }
        val script = decodeScript(bytes)
        println(
            "SCRIPT_$scriptId name=${script.name} opcodeCount=${script.opcodes.size} " +
                "intVarCount=${script.intVarCount} intArgCount=${script.intArgCount}",
        )
        println(" OPCODES=${script.opcodes.toList()}")
        script.intOperands?.let { println(" INT_OPERANDS=${it.toList()}") }
        script.stringOperands?.let { println(" STRING_OPERANDS=${it.toList()}") }
        script.switchTables.forEachIndexed { idx, table ->
            println(" SWITCH_TABLE_$idx=$table")
        }
        if (System.getProperty("probe.indexed") == "true") {
            for (idx in script.opcodes.indices) {
                val opcode = script.opcodes[idx]
                val operand = script.intOperands?.get(idx)?.takeIf { opcode != 3 }
                val str = script.stringOperands?.get(idx)
                println(" [$idx] op=$opcode intOperand=$operand strOperand=$str")
            }
        }
    }

    // ---- Component decode (ported from Component.decode()) ----

    private data class DecodedComponent(
        val type: Int,
        val name: String?,
        val text: String?,
        val layer: Int,
        val clientcode: Int,
        val opBase: String,
        val ops: List<String?>,
        val events: Int,
        val hooks: Map<String, List<Any>?>,
        val triggers: Map<String, IntArray?>,
        /** Archive-7 model id of a MODEL(6) component, -1 when none (65535 sentinel). */
        val modelId: Int = -1,
        /** Baked sprite id of a GRAPHIC(5) component, -1 when none. */
        val spriteId: Int = -1,
        /** Baked layout box, needed to tell an item-grid layer from a decorative one. */
        val x: Int = 0,
        val y: Int = 0,
        val width: Int = 0,
        val height: Int = 0,
    )

    private const val TYPE_LAYER = 0
    private const val TYPE_RECTANGLE = 3
    private const val TYPE_TEXT = 4
    private const val TYPE_GRAPHIC = 5
    private const val TYPE_MODEL = 6
    private const val TYPE_LINE = 9

    /** Model id of one raw component, -1 when the component is not a MODEL(6) or has none. */
    fun componentModelId(data: ByteArray): Int = decodeComponent(data).modelId

    /** The baked right-click op labels of one raw component (index 0 = op1). */
    fun componentOps(data: ByteArray): List<String?> = decodeComponent(data).ops

    /**
     * The baked `width x height` of one raw component. Exposed so a test can pin an interface's
     * own dimensions against the region the server chooses to open it in - a `190x261` root is a
     * sidebar panel, and opening one as a main-screen modal is a rendering bug the cache itself
     * can prove.
     */
    fun componentSize(data: ByteArray): Pair<Int, Int> = decodeComponent(data).let { it.width to it.height }

    /** Baked sprite id of one raw GRAPHIC(5) component, -1 when none. */
    fun componentSprite(data: ByteArray): Int = decodeComponent(data).spriteId

    /** The decoded hook argument lists (onLoad, onVarTransmit, ...) of one raw component; null entries are unset hooks. */
    fun componentHooks(data: ByteArray): Map<String, List<Any>?> = decodeComponent(data).hooks

    private fun decodeComponent(data: ByteArray): DecodedComponent {
        var modelId = -1
        var spriteId = -1
        val p = PacketReader(data)
        var version = p.g1()
        if (version == 255) version = -1

        var type = p.g1()
        var name: String? = null
        if ((type and 0x80) != 0) {
            type = type and 0x7F
            name = p.gjstr()
        }
        var text: String? = null

        val clientcode = p.g2()
        val originalX = p.g2s()
        val originalY = p.g2s()
        val originalWidth = p.g2()
        val originalHeight = p.g2()
        val resizeModeX = p.g1b()
        val resizeModeY = p.g1b()
        p.g1b()
        p.g1b() // reposModeX/Y
        val rawLayer = p.g2()
        val layer = if (rawLayer == 65535) -1 else rawLayer
        val flags = p.g1()
        if (version >= 0) {
            flags and 0x2 // noClickThrough, unused here
        }

        when (type) {
            TYPE_LAYER -> {
                p.g2()
                p.g2() // scrollWidth/Height
                if (version < 0) p.g1() // legacy noClickThrough byte
            }
            TYPE_GRAPHIC -> {
                // The baked sprite. Needed because a clientscript that overwrites a GRAPHIC with
                // IF_SETGRAPHIC (script 751 does exactly this to the Summoning orb's 747:3) has no
                // branch that puts the original back, so the only non-invented way to restore the
                // inactive state is to read what the cache itself bakes here.
                spriteId = p.g4().let { if (it == -1 || it == 0xFFFFFFFF.toInt()) -1 else it }
                p.g2() // angle2d
                p.g1() // spriteFlags
                p.g1()
                p.g1() // transparency/outline
                p.g4() // graphicShadow
                p.g1()
                p.g1() // horizontalFlip/verticalFlip
                p.g4() // colour
                if (version >= 3) p.g1() // clickMask
            }
            TYPE_MODEL -> {
                modelId = p.g2().let { if (it == 0xFFFF) -1 else it } // obj
                val modelFlags = p.g1()
                val ortho2d = (modelFlags and 0x1) == 1
                val orthoView = (modelFlags and 0x2) == 2
                if (ortho2d) {
                    p.g2s()
                    p.g2s() // modelOriginX/Y
                    p.g2()
                    p.g2()
                    p.g2()
                    p.g2() // xan2d/yan2d/zan2d/zoom2d
                } else if (orthoView) {
                    p.g2s()
                    p.g2s()
                    p.g2s() // modelOriginX/Y/Z
                    p.g2()
                    p.g2()
                    p.g2() // xan2d/yan2d/zan2d
                    p.g2s() // zoom2d
                }
                p.g2() // modelAnimation
                if (resizeModeX.toInt() != 0) p.g2() // modelAspectRatioX
                if (resizeModeY.toInt() != 0) p.g2() // modelAspectRatioY
            }
            TYPE_TEXT -> {
                p.g2() // fontGraphic
                if (version >= 2) p.g1() // fontMonospaced
                text = p.gjstr()
                p.g1()
                p.g1()
                p.g1()
                p.g1() // textHeight/AlignX/AlignY/textShadow
                p.g4() // colour
                p.g1() // transparency
                if (version >= 0) p.g1() // maxLines
            }
            TYPE_RECTANGLE -> {
                p.g4() // colour
                p.g1() // filled
                p.g1() // transparency
            }
            TYPE_LINE -> {
                p.g1() // lineWidth
                p.g4() // colour
                p.g1() // lineDirection
            }
        }

        val events = p.g3()

        var opkeyRate = p.g1()
        if (opkeyRate != 0) {
            while (opkeyRate != 0) {
                opkeyRate = p.g1() or (opkeyRate shl 8)
                opkeyRate = opkeyRate and 0xFFF
                if (opkeyRate == 4095) opkeyRate = -1
                p.g1b() // opKey
                p.g1b() // opChar
                opkeyRate = p.g1()
            }
        }

        val opBase = p.gjstr()

        val opFlags = p.g1()
        val opCount = opFlags and 0xF
        val ops = List<String?>(opCount) { p.gjstr() }

        val cursorCount = opFlags shr 4
        if (cursorCount > 0) {
            p.g1() // count
            p.g2() // opCursors[count]
        }
        if (cursorCount > 1) {
            p.g1()
            p.g2()
        }

        p.gjstr() // pauseText
        p.g1()
        p.g1()
        p.g1() // dragDeadZone/dragDeadTime/dragRenderBehaviour
        p.gjstr() // targetVerb

        val targetMask = (events shr 11) and 0x7F
        if (targetMask != 0) {
            p.g2()
            p.g2()
            p.g2() // targetParam/targetEnterCursor/targetEndCursor
        }
        if (version >= 0) p.g2() // mouseOverCursor

        if (version >= 0) {
            val intParamCount = p.g1()
            repeat(intParamCount) {
                p.g3()
                p.g4()
            }
            val stringParamCount = p.g1()
            repeat(stringParamCount) {
                p.g3()
                p.gjstr2()
            }
        }

        val hooks = linkedMapOf<String, List<Any>?>()
        hooks["onLoad"] = p.decodeHook()
        hooks["onMouseOver"] = p.decodeHook()
        hooks["onMouseLeave"] = p.decodeHook()
        hooks["onTargetLeave"] = p.decodeHook()
        hooks["onTargetEnter"] = p.decodeHook()
        hooks["onVarTransmit"] = p.decodeHook()
        hooks["onInvTransmit"] = p.decodeHook()
        hooks["onStatTransmit"] = p.decodeHook()
        hooks["onTimer"] = p.decodeHook()
        hooks["onOp"] = p.decodeHook()
        if (version >= 0) hooks["onOpT"] = p.decodeHook()
        hooks["onMouseRepeat"] = p.decodeHook()
        hooks["onClick"] = p.decodeHook()
        hooks["onClickRepeat"] = p.decodeHook()
        hooks["onRelease"] = p.decodeHook()
        hooks["onHold"] = p.decodeHook()
        hooks["onDrag"] = p.decodeHook()
        hooks["onDragComplete"] = p.decodeHook()
        hooks["onScrollWheel"] = p.decodeHook()
        hooks["onVarcTransmit"] = p.decodeHook()
        hooks["onVarcstrTransmit"] = p.decodeHook()

        val triggers = linkedMapOf<String, IntArray?>()
        triggers["varpTriggers"] = p.decodeTransmitList()
        triggers["inventoryTriggers"] = p.decodeTransmitList()
        triggers["statTriggers"] = p.decodeTransmitList()
        triggers["varcTriggers"] = p.decodeTransmitList()
        triggers["varcstrTriggers"] = p.decodeTransmitList()

        return DecodedComponent(
            type, name, text, layer, clientcode, opBase, ops, events, hooks, triggers, modelId, spriteId,
            originalX, originalY, originalWidth, originalHeight,
        )
    }

    // ---- ClientScript decode (ported from ClientScript.decode()) ----

    private data class DecodedScript(
        val name: String?,
        val opcodes: IntArray,
        val intOperands: IntArray?,
        val stringOperands: Array<String?>?,
        val intVarCount: Int,
        val intArgCount: Int,
        // one Map<caseValue, jumpTarget> per switch table, in declaration order - these are
        // the real SWITCH (opcode 51) case dispatch tables, stored separately from the opcode
        // stream in the script's metadata footer per ClientScript.decode().
        val switchTables: List<Map<Int, Int>>,
    )

    private fun decodeScript(data: ByteArray): DecodedScript {
        val p = PacketReader(data)
        p.pos = data.size - 2
        val footerLen = p.g2()
        val metaOffset = data.size - footerLen - 2 - 16
        p.pos = metaOffset
        val opcodeCount = p.g4()
        val intVarCount = p.g2()
        val stringVarCount = p.g2()
        val longVarCount = p.g2()
        val intArgCount = p.g2()
        val stringArgCount = p.g2()
        val longArgCount = p.g2()
        val switchTableCount = p.g1()
        val switchTables = mutableListOf<Map<Int, Int>>()
        for (i in 0 until switchTableCount) {
            var caseCount = p.g2()
            val table = linkedMapOf<Int, Int>()
            while (caseCount-- > 0) {
                val caseValue = p.g4()
                val jumpTarget = p.g4()
                table[caseValue] = jumpTarget
            }
            switchTables += table
        }
        // stringVarCount/longVarCount/stringArgCount/longArgCount are consumed above
        // for correct offset advancement only; not needed for this probe's output.
        stringVarCount; longVarCount; stringArgCount; longArgCount

        p.pos = 0
        val name = p.fastgstr()
        val opcodes = IntArray(opcodeCount)
        var intOperands: IntArray? = null
        var stringOperands: Array<String?>? = null
        var i = 0
        while (p.pos < metaOffset) {
            val opcode = p.g2()
            when {
                opcode == 3 -> {
                    if (stringOperands == null) stringOperands = arrayOfNulls(opcodeCount)
                    stringOperands[i] = p.gjstr()
                }
                opcode == 54 -> {
                    p.g8() // longOperands, discarded - not needed for this probe
                }
                else -> {
                    if (intOperands == null) intOperands = IntArray(opcodeCount)
                    intOperands[i] =
                        if (opcode >= 150 || opcode == 21 || opcode == 38 || opcode == 39) {
                            p.g1()
                        } else {
                            p.g4()
                        }
                }
            }
            opcodes[i++] = opcode
        }

        return DecodedScript(name, opcodes, intOperands, stringOperands, intVarCount, intArgCount, switchTables)
    }

    // ---- Packet primitive reader (ported from com.jagex.core.io.Packet) ----

    private class PacketReader(val data: ByteArray) {
        var pos = 0

        fun g1(): Int = data[pos++].toInt() and 0xFF

        fun g1b(): Byte = data[pos++]

        fun g2(): Int {
            pos += 2
            return ((data[pos - 2].toInt() and 0xFF) shl 8) + (data[pos - 1].toInt() and 0xFF)
        }

        fun g2s(): Int {
            pos += 2
            var value = (data[pos - 1].toInt() and 0xFF) + ((data[pos - 2].toInt() and 0xFF) shl 8)
            if (value > Short.MAX_VALUE) value -= 65536
            return value
        }

        fun g3(): Int {
            pos += 3
            return ((data[pos - 3].toInt() and 0xFF) shl 16) +
                ((data[pos - 2].toInt() and 0xFF) shl 8) +
                (data[pos - 1].toInt() and 0xFF)
        }

        fun g4(): Int {
            pos += 4
            return ((data[pos - 4].toInt() and 0xFF) shl 24) +
                ((data[pos - 3].toInt() and 0xFF) shl 16) +
                ((data[pos - 2].toInt() and 0xFF) shl 8) +
                (data[pos - 1].toInt() and 0xFF)
        }

        fun g8(): Long {
            val upper = g4().toLong() and 0xFFFFFFFFL
            val lower = g4().toLong() and 0xFFFFFFFFL
            return lower + (upper shl 32)
        }

        fun gjstr(): String {
            val off = pos
            while (data[pos++].toInt() != 0) { /* empty */ }
            val length = pos - off - 1
            return if (length == 0) "" else String(data, off, length, Charsets.ISO_8859_1)
        }

        fun gjstr2(): String {
            val version = data[pos++]
            check(version.toInt() == 0) { "Bad version number in gjstr2" }
            val start = pos
            while (data[pos++].toInt() != 0) { /* empty */ }
            val length = pos - start - 1
            return if (length == 0) "" else String(data, start, length, Charsets.ISO_8859_1)
        }

        fun fastgstr(): String? {
            if (data[pos] == 0.toByte()) {
                pos++
                return null
            }
            return gjstr()
        }

        fun decodeHook(): List<Any>? {
            val count = g1()
            if (count == 0) return null
            val args = mutableListOf<Any>()
            for (i in 0 until count) {
                val type = g1()
                if (type == 0) args += g4() else args += gjstr()
            }
            return args
        }

        fun decodeTransmitList(): IntArray? {
            val count = g1()
            if (count == 0) return null
            return IntArray(count) { g4() }
        }
    }
}

/**
 * Every archive-7 model id referenced by a MODEL(6) interface component in the cache, for the
 * model-namespace census. Uses the same byte-exact `Component.decode()` port as the hook probe.
 */
object InterfaceModelReferences {
    fun collect(
        library: CacheLibrary,
        record: (id: Int, role: String) -> Unit,
    ): Int {
        val index = library.index(3)
        var components = 0
        index.archiveIds().forEach { interfaceId ->
            val archive = index.archive(interfaceId) ?: return@forEach
            archive.fileIds().forEach { slot ->
                val bytes = archive.file(slot)?.data ?: return@forEach
                components++
                val modelId = InterfaceHookProbeTool.componentModelId(bytes)
                if (modelId != -1) record(modelId, "interface_model")
            }
        }
        return components
    }
}
