package gg.rsmod.plugins.content.npcs

import com.google.gson.JsonArray
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import gg.rsmod.game.fs.def.NpcDef
import gg.rsmod.game.model.World
import gg.rsmod.game.model.entity.Npc
import gg.rsmod.game.model.queue.QueueTask
import gg.rsmod.plugins.api.cfg.FacialExpression
import gg.rsmod.plugins.api.ext.chatNpc
import gg.rsmod.plugins.api.ext.chatPlayer
import gg.rsmod.plugins.api.ext.messageBox
import gg.rsmod.plugins.api.ext.options
import gg.rsmod.plugins.api.ext.player
import gg.rsmod.plugins.content.inter.bank.openBank
import gg.rsmod.util.TextWrapping
import java.io.File
import java.io.FileReader

/**
 * Real conversations for every npc that has no hand-written dialogue (owner 2026-09-21 "the chatdialoges need to be good for every
 * talkable and tradeable npcs", 2026-09-23 "a lot of npcs just say 1 thing then stop ... fix this for every NPC").
 *
 * `data/cfg/npcs/transcript-dialogue.json` is generated by `C:\RSPS\tools\npc-dialogue` from the RuneScape Wiki transcripts: the npc
 * id resolves to its own wiki page through the wiki's `infobox_npc` bucket (so "Bartender" 731 gets "Transcript:Bartender (Jolly Boar
 * Inn)", not another inn's), with the Old School wiki transcript by name as the fallback. Every row records its source page and
 * revision. The tree keeps the transcript's options, branches, random variants, purchases (`removes=`/`receives=`, item names
 * resolved to this cache's ids) and shop/bank openings; see the generator's docstring for the node types.
 *
 * Runtime rules: money/space conditions are real checks; random variants are rolled; a quest-state condition takes its "not yet"
 * branch (quests are parked); an exchange only happens when the player holds everything it takes and has room for what it gives.
 */
object TranscriptDialogue {
    const val PATH = "./data/cfg/npcs/transcript-dialogue.json"
    private const val COINS = 995
    private const val MAX_JUMPS = 40

    @Volatile
    private var rows: Map<Int, JsonObject> = emptyMap()

    fun load(file: File = File(PATH)): Int {
        if (!file.exists()) return 0
        val root: JsonObject = FileReader(file).use { JsonParser().parse(it).asJsonObject }
        rows = root.entrySet().associate { e -> e.key.toInt() to e.value.asJsonObject }
        return rows.size
    }

    fun has(npcId: Int): Boolean = npcId in rows

    fun source(npcId: Int): String? = rows[npcId]?.get("src")?.asString

    private enum class Flow { NEXT, END, RESTART, BACK }

    private class Ctx(val npc: Npc, val top: JsonArray) {
        var jumps = 0
        val optionStack = ArrayList<JsonObject>()
    }

    suspend fun play(
        task: QueueTask,
        npc: Npc,
    ): Boolean {
        val row = rows[npc.id] ?: return false
        val ctx = Ctx(npc, row.getAsJsonArray("nodes"))
        var flow = run(task, ctx, ctx.top)
        while (flow == Flow.RESTART && ctx.jumps++ < MAX_JUMPS) flow = run(task, ctx, ctx.top)
        return true
    }

    private suspend fun run(
        task: QueueTask,
        ctx: Ctx,
        nodes: JsonArray,
    ): Flow {
        for (el in nodes) {
            val n = el.asJsonObject
            val flow =
                when (n["t"].asString) {
                    "npc" -> {
                        task.chatNpc(n["x"].asString, facialExpression = expression(n))
                        Flow.NEXT
                    }
                    "player" -> {
                        task.chatPlayer(n["x"].asString, facialExpression = expression(n))
                        Flow.NEXT
                    }
                    "other" -> {
                        val speaker = n["s"].asString
                        val other = npcByName(ctx.npc.world, speaker)
                        task.chatNpc(n["x"].asString, npc = other ?: ctx.npc.id, facialExpression = expression(n), title = speaker)
                        Flow.NEXT
                    }
                    "msg" -> {
                        val lines = TextWrapping.wrap(n["x"].asString)?.toList() ?: listOf(n["x"].asString)
                        lines.chunked(4).forEach { task.messageBox(*it.toTypedArray()) }
                        Flow.NEXT
                    }
                    "opt" -> options(task, ctx, n)
                    "rnd" -> {
                        val branches = n.getAsJsonArray("o")
                        if (branches.size() == 0) Flow.NEXT else run(task, ctx, branches[ctx.npc.world.random(branches.size() - 1)].asJsonArray)
                    }
                    "cond" -> run(task, ctx, pick(task, ctx, n.getAsJsonArray("b")))
                    "trade" -> {
                        exchange(task, n)
                        Flow.NEXT
                    }
                    "open" -> {
                        open(task, ctx, n["x"].asString)
                        Flow.END
                    }
                    "go" ->
                        when (n["to"].asString) {
                            "initial" -> Flow.RESTART
                            "options" -> Flow.BACK
                            else -> Flow.END
                        }
                    else -> Flow.NEXT
                }
            if (flow != Flow.NEXT) return flow
        }
        return Flow.NEXT
    }

    private suspend fun options(
        task: QueueTask,
        ctx: Ctx,
        node: JsonObject,
    ): Flow {
        val choices = node.getAsJsonArray("o")
        if (choices.size() == 0) return Flow.NEXT
        ctx.optionStack += node
        try {
            while (true) {
                val texts = choices.map { it.asJsonArray[0].asString }.take(MAX_OPTIONS)
                val picked = task.options(*texts.toTypedArray(), title = node["title"]?.asString ?: "Select an Option")
                if (picked < 1 || picked > texts.size) return Flow.END
                val flow = run(task, ctx, choices[picked - 1].asJsonArray[1].asJsonArray)
                // "back to the options" repeats this menu; anything else leaves it.
                if (flow == Flow.BACK && ctx.jumps++ < MAX_JUMPS) continue
                return if (flow == Flow.BACK) Flow.END else flow
            }
        } finally {
            ctx.optionStack.removeAt(ctx.optionStack.size - 1)
        }
    }

    private const val MAX_OPTIONS = 5

    /** Picks the branch of a condition node: real money/space checks, rolled variants, else the default/"not yet" branch. */
    private fun pick(
        task: QueueTask,
        ctx: Ctx,
        branches: JsonArray,
    ): JsonArray {
        val list = branches.map { it.asJsonArray }
        fun kind(b: JsonArray) = b[0].asString
        fun body(b: JsonArray) = b[2].asJsonArray
        val player = task.player
        // "If you have any bear furs in your inventory" / "If you do not have a ...": real inventory checks, in page order.
        fun itemHolds(k: String): Boolean? =
            when {
                k.startsWith("has_item:") -> player.inventory.contains(k.substringAfter(':').toInt())
                k.startsWith("lacks_item:") -> !player.inventory.contains(k.substringAfter(':').toInt())
                else -> null
            }
        if (list.any { itemHolds(kind(it)) != null }) {
            list.firstOrNull { itemHolds(kind(it)) == true }?.let { return body(it) }
            val rest = list.filter { itemHolds(kind(it)) == null }
            return if (rest.isEmpty()) JsonArray() else body(rest.firstOrNull { kind(it) == "default" } ?: rest.first())
        }
        list.firstOrNull { kind(it) == "money_ok" }?.let { ok ->
            val trade = firstTrade(body(ok))
            val affordable = trade == null || takes(trade).all { (item, amount) -> player.inventory.getItemCount(item) >= amount }
            val chosen = if (affordable) ok else list.firstOrNull { kind(it) == "money_no" }
            if (chosen != null) return body(chosen)
        }
        list.firstOrNull { kind(it) == "money_no" }?.let { no ->
            val trade = list.firstNotNullOfOrNull { b -> firstTrade(body(b)) }
            val affordable = trade != null && takes(trade).all { (item, amount) -> player.inventory.getItemCount(item) >= amount }
            return body(if (affordable) list.firstOrNull { it !== no } ?: no else no)
        }
        list.firstOrNull { kind(it) == "space_ok" || kind(it) == "space_no" }?.let {
            val hasSpace = player.inventory.freeSlotCount > 0
            list.firstOrNull { b -> kind(b) == if (hasSpace) "space_ok" else "space_no" }?.let { return body(it) }
        }
        val random = list.filter { kind(it) == "random" }
        if (random.isNotEmpty()) return body(random[ctx.npc.world.random(random.size - 1)])
        return body(list.firstOrNull { kind(it) == "default" } ?: list.first())
    }

    private fun firstTrade(nodes: JsonArray): JsonObject? {
        for (el in nodes) {
            val n = el.asJsonObject
            if (n["t"].asString == "trade") return n
        }
        return null
    }

    private fun takes(trade: JsonObject): List<Pair<Int, Int>> = trade.getAsJsonArray("rm").map { it.asJsonArray.let { a -> a[0].asInt to a[1].asInt } }

    private fun gives(trade: JsonObject): List<Pair<Int, Int>> = trade.getAsJsonArray("add").map { it.asJsonArray.let { a -> a[0].asInt to a[1].asInt } }

    /** All-or-nothing exchange: nothing moves unless the player holds every taken stack and has room for every given one. */
    private fun exchange(
        task: QueueTask,
        trade: JsonObject,
    ) {
        val player = task.player
        val take = takes(trade)
        val give = gives(trade)
        if (take.isEmpty()) return
        if (take.any { (item, amount) -> player.inventory.getItemCount(item) < amount }) return
        val slotsNeeded = give.count { (item, _) -> !player.inventory.contains(item) || !isStackable(task, item) }
        val freed = take.count { (item, amount) -> player.inventory.getItemCount(item) == amount && !isStackable(task, item) }
        if (player.inventory.freeSlotCount + freed < slotsNeeded) return
        take.forEach { (item, amount) -> player.inventory.remove(item, amount) }
        give.forEach { (item, amount) -> player.inventory.add(item, amount) }
    }

    private fun isStackable(
        task: QueueTask,
        item: Int,
    ): Boolean = item == COINS || task.player.world.definitions.getNullable(gg.rsmod.game.fs.def.ItemDef::class.java, item)?.stackable == true

    private fun open(
        task: QueueTask,
        ctx: Ctx,
        what: String,
    ) {
        val player = task.player
        if (what.contains("bank", ignoreCase = true)) {
            player.openBank()
            return
        }
        val def = ctx.npc.world.definitions.get(NpcDef::class.java, ctx.npc.id)
        val slot = def.options.indexOfFirst { it != null && it.lowercase() in SHOP_OPTIONS }
        if (slot != -1 && (slot + 1) in ctx.npc.world.plugins.boundNpcOptions(ctx.npc.id)) {
            ctx.npc.world.plugins.executeNpc(player, ctx.npc.id, slot + 1)
        }
    }

    private val SHOP_OPTIONS = setOf("trade", "trade-with", "shop", "open-store", "buy")

    private fun expression(n: JsonObject): FacialExpression =
        n["e"]?.asString?.let { runCatching { FacialExpression.valueOf(it) }.getOrNull() } ?: FacialExpression.CALM_TALK

    @Volatile
    private var byName: Map<String, Int>? = null

    private fun npcByName(
        world: World,
        name: String,
    ): Int? {
        val map =
            byName ?: world.definitions.getAllKeys(NpcDef::class.java).sorted().mapNotNull { id ->
                world.definitions.getNullable(NpcDef::class.java, id)?.name?.lowercase()?.let { it to id }
            }.distinctBy { it.first }.toMap().also { byName = it }
        return map[name.lowercase()]
    }
}
