package gg.rsmod.plugins.content.combat.strategy.magic

import gg.rsmod.game.model.Graphic
import gg.rsmod.plugins.api.cfg.Anims
import gg.rsmod.plugins.api.cfg.Gfx
import gg.rsmod.plugins.api.Skills
import gg.rsmod.plugins.api.cfg.Items

private val ZURIELS_STAVES = intArrayOf(Items.ZURIELS_STAFF, Items.ZURIELS_STAFF_DEG, Items.CORRUPT_ZURIELS_STAFF, Items.CORRUPT_ZURIELS_STAFF_DEG)
private const val ZURIELS_MESSAGE = "You need to be wielding Zuriel's staff to cast this spell."

/**
 * @author Tom <rspsmods@gmail.com>
 */
enum class CombatSpell(
    val uniqueId: Int,
    val componentId: Int,
    val maxHit: Int,
    val castGfx: Graphic?,
    val castAnimation: Array<Int>,
    val projectile: Int,
    val secondProjectile: Int = -1,
    val thirdProjectile: Int = -1,
    val impactGfx: Graphic?,
    val autoCastId: Int,
    val experience: Double = 0.0,
    /** Spellbook interface the spell lives in: 192 standard, 193 Ancient Magicks. */
    val interfaceId: Int = 192,
    /** Burst/Barrage: hit every pawn within 1 tile of the target when both are in a multi-way area. */
    val multiTarget: Boolean = false,
    /** Secondary effect applied on a successful cast. */
    val effect: SpellEffect? = null,
    /** When non-empty the caster must wield one of these weapons (Iban Blast, Magic Dart, Miasmic, Storm of Armadyl). */
    val requiredWeapons: IntArray = intArrayOf(),
    /** Weapon-requirement failure message. */
    val requiredWeaponMessage: String = "",
    /** Effect-only spells (Bind, Confuse, Teleport Block) roll accuracy but never show a damage hit. */
    val damaging: Boolean = true,
    /** Delay (cycles) before the impact graphic/hit when the spell has no projectile; -1 = use projectile lifespan. */
    val fixedHitDelay: Int = -1,
) {
    /**
     * Standard.
     */

    WIND_RUSH(
        uniqueId = 3759,
        componentId = 98,
        maxHit = 1,
        castGfx = Graphic(Gfx.WIND_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.WIND_SPELL, Anims.WIND_SPELL_WITH_STAFF),
        projectile = Gfx.WIND_RUSH_PROJ,
        impactGfx = Graphic(Gfx.WIND_RUSH_IMPACT, 32),
        autoCastId = 143,
        experience = 0.2,
    ),

    WIND_STRIKE(
        uniqueId = 15,
        componentId = 25,
        maxHit = 2,
        castGfx = Graphic(Gfx.WIND_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.WIND_SPELL, Anims.WIND_SPELL_WITH_STAFF),
        projectile = Gfx.WIND_STRIKE_PROJ,
        impactGfx = Graphic(Gfx.WIND_STRIKE_IMPACT, 32),
        autoCastId = 3,
        experience = 5.5,
    ),

    WATER_STRIKE(
        uniqueId = 17,
        componentId = 28,
        maxHit = 4,
        castGfx = Graphic(Gfx.WATER_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.WATER_SPELL, Anims.WATER_SPELL_WITH_STAFF),
        projectile = Gfx.WATER_STRIKE_PROJ,
        impactGfx = Graphic(Gfx.WATER_STRIKE_IMPACT, 32),
        autoCastId = 5,
        experience = 7.5,
    ),

    EARTH_STRIKE(
        uniqueId = 19,
        componentId = 30,
        maxHit = 6,
        castGfx = Graphic(Gfx.EARTH_SPELL_CAST, -4),
        castAnimation = arrayOf(Anims.EARTH_SPELL, Anims.EARTH_SPELL_WITH_STAFF),
        projectile = Gfx.EARTH_STRIKE_PROJ,
        impactGfx = Graphic(Gfx.EARTH_STRIKE_IMPACT, 60),
        autoCastId = 7,
        experience = 9.5,
    ),

    FIRE_STRIKE(
        uniqueId = 71,
        componentId = 32,
        maxHit = 8,
        castGfx = Graphic(Gfx.FIRE_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.FIRE_SPELL, Anims.FIRE_SPELL_WITH_STAFF),
        projectile = Gfx.FIRE_STRIKE_PROJ,
        impactGfx = Graphic(Gfx.FIRE_STRIKE_IMPACT, 32),
        autoCastId = 9,
        experience = 11.5,
    ),

    WIND_BOLT(
        uniqueId = 73,
        componentId = 34,
        maxHit = 9,
        castGfx = Graphic(Gfx.WIND_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.WIND_SPELL, Anims.WIND_SPELL_WITH_STAFF),
        projectile = Gfx.WIND_BOLT_PROJ,
        impactGfx = Graphic(Gfx.WIND_BLAST_IMPACT, 32),
        autoCastId = 11,
        experience = 13.5,
    ),

    WATER_BOLT(
        uniqueId = 76,
        componentId = 39,
        maxHit = 10,
        castGfx = Graphic(Gfx.WATER_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.WATER_SPELL, Anims.WATER_SPELL_WITH_STAFF),
        projectile = Gfx.WATER_BOLT_PROJ,
        impactGfx = Graphic(Gfx.WATER_BOLT_IMPACT, 32),
        autoCastId = 13,
        experience = 16.5,
    ),

    EARTH_BOLT(
        uniqueId = 79,
        componentId = 42,
        maxHit = 11,
        castGfx = Graphic(Gfx.EARTH_BOLT_CAST, 22),
        castAnimation = arrayOf(Anims.EARTH_SPELL, Anims.EARTH_SPELL_WITH_STAFF),
        projectile = Gfx.EARTH_BOLT_PROJ,
        impactGfx = Graphic(Gfx.EARTH_BOLT_IMPACT, 32),
        autoCastId = 15,
        experience = 19.5,
    ),

    FIRE_BOLT(
        uniqueId = 82,
        componentId = 45,
        maxHit = 12,
        castGfx = Graphic(Gfx.FIRE_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.FIRE_SPELL, Anims.FIRE_SPELL_WITH_STAFF),
        projectile = Gfx.FIRE_BOLT_PROJ,
        impactGfx = Graphic(Gfx.FIRE_BOLT_IMPACT, 32),
        autoCastId = 17,
        experience = 22.5,
    ),

    WIND_BLAST(
        uniqueId = 85,
        componentId = 49,
        maxHit = 13,
        castGfx = Graphic(Gfx.WIND_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.WIND_SPELL, Anims.WIND_SPELL_WITH_STAFF),
        projectile = Gfx.WIND_BLAST_PROJ,
        impactGfx = Graphic(Gfx.WIND_BLAST_IMPACT, 32),
        autoCastId = 19,
        experience = 25.5,
    ),

    WATER_BLAST(
        uniqueId = 88,
        componentId = 52,
        maxHit = 14,
        castGfx = Graphic(Gfx.WATER_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.WATER_SPELL, Anims.WATER_SPELL_WITH_STAFF),
        projectile = Gfx.WATER_BLAST_PROJ,
        impactGfx = Graphic(Gfx.WATER_BLAST_IMPACT, 32),
        autoCastId = 21,
        experience = 28.5,
    ),

    EARTH_BLAST(
        uniqueId = 90,
        componentId = 58,
        maxHit = 15,
        castGfx = Graphic(Gfx.EARTH_BLAST_CAST, 22),
        castAnimation = arrayOf(Anims.EARTH_SPELL, Anims.EARTH_SPELL_WITH_STAFF),
        projectile = Gfx.EARTH_BLAST_PROJ,
        impactGfx = Graphic(Gfx.EARTH_BLAST_IMPACT, 32),
        autoCastId = 23,
        experience = 31.5,
    ),

    FIRE_BLAST(
        uniqueId = 95,
        componentId = 63,
        maxHit = 16,
        castGfx = Graphic(Gfx.FIRE_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.FIRE_SPELL, Anims.FIRE_SPELL_WITH_STAFF),
        projectile = Gfx.FIRE_BLAST_PROJ,
        secondProjectile = Gfx.FIRE_BLAST_PROJ_2,
        impactGfx = Graphic(Gfx.FIRE_BLAST_IMPACT, 32),
        autoCastId = 25,
        experience = 34.5,
    ),

    SARADOMIN_STRIKE(
        uniqueId = 501,
        componentId = 66,
        maxHit = 20,
        castGfx = Graphic(Gfx.RESET, 0),
        castAnimation = arrayOf(Anims.SPELL_GODSTAVE, Anims.SPELL_GODSTAVE),
        projectile = Gfx.GFX_0,
        secondProjectile = Gfx.GFX_0,
        impactGfx = Graphic(Gfx.SARADOMIN_STRIKE_IMPACT, 100),
        autoCastId = 26,
        experience = 34.5,
    ),

    CLAWS_OF_GUTHIX(
        uniqueId = 502,
        componentId = 67,
        maxHit = 20,
        castGfx = Graphic(Gfx.RESET, 0),
        castAnimation = arrayOf(Anims.SPELL_GODSTAVE, Anims.SPELL_GODSTAVE, Anims.CLAWS_OF_GUTHIX),
        projectile = Gfx.GFX_0,
        secondProjectile = Gfx.GFX_0,
        impactGfx = Graphic(Gfx.CLAWS_OF_GUTHIX_IMPACT, 100),
        autoCastId = 28,
        experience = 34.5,
    ),

    FLAMES_OF_ZAMORAK(
        uniqueId = 503,
        componentId = 68,
        maxHit = 20,
        castGfx = Graphic(Gfx.RESET, 0),
        castAnimation = arrayOf(Anims.SPELL_GODSTAVE, Anims.SPELL_GODSTAVE),
        projectile = Gfx.GFX_0,
        secondProjectile = Gfx.GFX_0,
        impactGfx = Graphic(Gfx.FLAMES_OF_ZAMORAK_IMPACT, 0),
        autoCastId = 30,
        experience = 34.5,
    ),

    WIND_WAVE(
        uniqueId = 96,
        componentId = 70,
        maxHit = 17,
        castGfx = Graphic(Gfx.WIND_SPELL_CAST, 22),
        castAnimation = arrayOf(gg.rsmod.plugins.content.items.osrs.OsrsSeq.HUMAN_CAST_SURGE, gg.rsmod.plugins.content.items.osrs.OsrsSeq.HUMAN_CAST_SURGE), // OSRS 7855 HUMAN_CAST_SURGE (owner 2026-09-19)
        projectile = Gfx.WIND_WAVE_PROJ,
        impactGfx = Graphic(Gfx.WIND_WAVE_IMPACT, height = 32),
        autoCastId = 27,
        experience = 36.0,
    ),

    WATER_WAVE(
        uniqueId = 98,
        componentId = 73,
        maxHit = 18,
        castGfx = Graphic(Gfx.WATER_SPELL_CAST, 22),
        castAnimation = arrayOf(gg.rsmod.plugins.content.items.osrs.OsrsSeq.HUMAN_CAST_SURGE, gg.rsmod.plugins.content.items.osrs.OsrsSeq.HUMAN_CAST_SURGE), // OSRS 7855 HUMAN_CAST_SURGE (owner 2026-09-19)
        projectile = Gfx.WATER_WAVE_PROJ,
        impactGfx = Graphic(Gfx.WATER_WAVE_IMPACT, 32),
        autoCastId = 29,
        experience = 37.5,
    ),

    EARTH_WAVE(
        uniqueId = 101,
        componentId = 77,
        maxHit = 19,
        castGfx = Graphic(Gfx.EARTH_WAVE_CAST, 22),
        castAnimation = arrayOf(gg.rsmod.plugins.content.items.osrs.OsrsSeq.HUMAN_CAST_SURGE, gg.rsmod.plugins.content.items.osrs.OsrsSeq.HUMAN_CAST_SURGE), // OSRS 7855 HUMAN_CAST_SURGE (owner 2026-09-19)
        projectile = Gfx.EARTH_WAVE_PROJ,
        impactGfx = Graphic(Gfx.EARTH_WAVE_IMPACT, 32),
        autoCastId = 31,
        experience = 40.0,
    ),

    FIRE_WAVE(
        uniqueId = 102,
        componentId = 80,
        maxHit = 20,
        castGfx = Graphic(Gfx.FIRE_SPELL_CAST, 22),
        castAnimation = arrayOf(gg.rsmod.plugins.content.items.osrs.OsrsSeq.HUMAN_CAST_SURGE, gg.rsmod.plugins.content.items.osrs.OsrsSeq.HUMAN_CAST_SURGE), // OSRS 7855 HUMAN_CAST_SURGE (owner 2026-09-19)
        projectile = Gfx.FIRE_WAVE_PROJ,
        secondProjectile = Gfx.FIRE_WAVE_PROJ_2,
        thirdProjectile = Gfx.FIRE_WAVE_PROJ_2,
        impactGfx = Graphic(Gfx.FIRE_WAVE_IMPACT, 32),
        autoCastId = 33,
        experience = 42.5,
    ),

    WIND_SURGE(
        uniqueId = 815,
        componentId = 84,
        maxHit = 21,
        castGfx = Graphic(Gfx.WIND_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.WIND_SPELL, Anims.WIND_SPELL_WITH_STAFF),
        projectile = Gfx.WIND_WAVE_PROJ,
        impactGfx = Graphic(Gfx.WIND_SURGE_IMPACT, 96),
        autoCastId = 47,
        experience = 44.5,
    ),

    WATER_SURGE(
        uniqueId = 816,
        componentId = 87,
        maxHit = 22,
        castGfx = Graphic(Gfx.WATER_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.WATER_SPELL, Anims.WATER_SPELL_WITH_STAFF),
        projectile = Gfx.WATER_SURGE_PROJ,
        impactGfx = Graphic(Gfx.WATER_SURGE_IMPACT, 32),
        autoCastId = 49,
        experience = 46.5,
    ),

    EARTH_SURGE(
        uniqueId = 817,
        componentId = 89,
        maxHit = 23,
        castGfx = Graphic(Gfx.EARTH_SURGE_CAST, 22),
        castAnimation = arrayOf(Anims.EARTH_SPELL, Anims.EARTH_SPELL_WITH_STAFF),
        projectile = Gfx.EARTH_SURGE_PROJ,
        impactGfx = Graphic(Gfx.EARTH_SURGE_IMPACT, 32),
        autoCastId = 51,
        experience = 48.5,
    ),

    FIRE_SURGE(
        uniqueId = 818,
        componentId = 91,
        maxHit = 24,
        castGfx = Graphic(Gfx.FIRE_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.FIRE_SPELL, Anims.FIRE_SPELL_WITH_STAFF),
        projectile = Gfx.FIRE_SURGE_PROJ,
        secondProjectile = Gfx.FIRE_SURGE_PROJ_2,
        thirdProjectile = Gfx.FIRE_SURGE_PROJ_2,
        impactGfx = Graphic(Gfx.FIRE_SURGE_IMPACT, 32),
        autoCastId = 53,
        experience = 50.5,
    ),

    /**
     * Standard spellbook: effect spells, staff spells and Teleport Block.
     *
     * Animation/graphic/projectile ids sourced from the 2009scape modern spell handlers
     * (BindSpell, CurseSpells, CrumbleUndead, IbanBlast, MagicDart, TeleblockSpell) and cross-checked
     * against Matrix 718 PlayerCombat; levels/runes come from the production cache (SpellbookData).
     * Max hits and experience follow the 2011 RuneScape Wiki (Ice Barrage 30, Iban Blast 25, ...).
     */

    CONFUSE(
        uniqueId = 16,
        componentId = 26,
        maxHit = 0,
        castGfx = Graphic(102, 96),
        castAnimation = arrayOf(716, 716),
        projectile = 103,
        impactGfx = Graphic(104, 96),
        autoCastId = -1,
        experience = 13.0,
        effect = SpellEffect.StatDrain(Skills.ATTACK, 5),
        damaging = false,
    ),
    WEAKEN(
        uniqueId = 20,
        componentId = 31,
        maxHit = 0,
        castGfx = Graphic(105, 96),
        castAnimation = arrayOf(716, 716),
        projectile = 106,
        impactGfx = Graphic(107, 96),
        autoCastId = -1,
        experience = 21.0,
        effect = SpellEffect.StatDrain(Skills.STRENGTH, 5),
        damaging = false,
    ),
    CURSE(
        uniqueId = 24,
        componentId = 35,
        maxHit = 0,
        castGfx = Graphic(108, 96),
        castAnimation = arrayOf(716, 716),
        projectile = 109,
        impactGfx = Graphic(110, 96),
        autoCastId = -1,
        experience = 29.0,
        effect = SpellEffect.StatDrain(Skills.DEFENCE, 5),
        damaging = false,
    ),
    BIND(
        uniqueId = 319,
        componentId = 36,
        maxHit = 0,
        castGfx = Graphic(177, 96),
        castAnimation = arrayOf(710, 710),
        projectile = 178,
        impactGfx = Graphic(181, 96),
        autoCastId = -1,
        experience = 30.0,
        effect = SpellEffect.Freeze(8),
        damaging = false,
    ),
    SNARE(
        uniqueId = 320,
        componentId = 55,
        maxHit = 0,
        castGfx = Graphic(177, 96),
        castAnimation = arrayOf(710, 710),
        projectile = 178,
        impactGfx = Graphic(180, 96),
        autoCastId = -1,
        experience = 60.0,
        effect = SpellEffect.Freeze(16),
        damaging = false,
    ),
    ENTANGLE(
        uniqueId = 321,
        componentId = 81,
        maxHit = 0,
        castGfx = Graphic(177, 96),
        castAnimation = arrayOf(710, 710),
        projectile = 178,
        impactGfx = Graphic(179, 96),
        autoCastId = -1,
        experience = 89.0,
        effect = SpellEffect.Freeze(24),
        damaging = false,
    ),
    VULNERABILITY(
        uniqueId = 56,
        componentId = 75,
        maxHit = 0,
        castGfx = Graphic(167, 96),
        castAnimation = arrayOf(729, 729),
        projectile = 168,
        impactGfx = Graphic(169, 96),
        autoCastId = -1,
        experience = 76.0,
        effect = SpellEffect.StatDrain(Skills.DEFENCE, 10),
        damaging = false,
    ),
    ENFEEBLE(
        uniqueId = 57,
        componentId = 78,
        maxHit = 0,
        castGfx = Graphic(170, 96),
        castAnimation = arrayOf(729, 729),
        projectile = 171,
        impactGfx = Graphic(172, 96),
        autoCastId = -1,
        experience = 83.0,
        effect = SpellEffect.StatDrain(Skills.STRENGTH, 10),
        damaging = false,
    ),
    STUN(
        uniqueId = 58,
        componentId = 82,
        maxHit = 0,
        castGfx = Graphic(173, 96),
        castAnimation = arrayOf(729, 729),
        projectile = 174,
        impactGfx = Graphic(175, 96),
        autoCastId = -1,
        experience = 90.0,
        effect = SpellEffect.StatDrain(Skills.ATTACK, 10),
        damaging = false,
    ),
    TELEPORT_BLOCK(
        uniqueId = 1565,
        componentId = 86,
        maxHit = 0,
        castGfx = Graphic(1841, 0),
        castAnimation = arrayOf(gg.rsmod.plugins.content.items.osrs.OsrsSeq.HUMAN_CASTING_TELE_BLOCK, gg.rsmod.plugins.content.items.osrs.OsrsSeq.HUMAN_CASTING_TELE_BLOCK_STAFF), // OSRS 1819 / 1820 (owner 2026-09-19)
        projectile = 1842,
        impactGfx = Graphic(1843, 0),
        autoCastId = -1,
        experience = 80.0,
        effect = SpellEffect.Teleblock,
        damaging = false,
    ),
    CRUMBLE_UNDEAD(
        uniqueId = 34,
        componentId = 47,
        maxHit = 15,
        castGfx = Graphic(145, 96),
        castAnimation = arrayOf(724, 724),
        projectile = 146,
        impactGfx = Graphic(147, 96),
        autoCastId = 35,
        experience = 24.5,
    ),
    IBAN_BLAST(
        uniqueId = 53,
        componentId = 54,
        maxHit = 25,
        castGfx = Graphic(87, 96),
        castAnimation = arrayOf(708, 708),
        projectile = 88,
        impactGfx = Graphic(89, 96),
        autoCastId = 45,
        experience = 30.0,
        requiredWeapons = intArrayOf(Items.IBANS_STAFF, Items.IBANS_STAFF_1410),
        requiredWeaponMessage = "You need to be wielding Iban's staff to cast this spell.",
    ),
    MAGIC_DART(
        uniqueId = 324,
        componentId = 56,
        maxHit = 19,
        castGfx = null,
        castAnimation = arrayOf(1576, 1576),
        projectile = 328,
        impactGfx = Graphic(329, 96),
        autoCastId = 37,
        experience = 30.0,
        // OSRS Wiki "Staff of the Dead": it can autocast Magic Dart; the toxic staff "shares the same features".
        // OSRS Wiki "Staff of Balance": autocast "Includes Crumble Undead, Magic Dart, and Claws of Guthix".
        requiredWeapons = intArrayOf(Items.SLAYERS_STAFF, Items.STAFF_OF_LIGHT, Items.STAFF_OF_THE_DEAD, Items.TOXIC_STAFF_UNCHARGED, Items.TOXIC_STAFF_OF_THE_DEAD, Items.STAFF_OF_BALANCE),
        requiredWeaponMessage = "You need to be wielding a slayer's staff or staff of light to cast this spell.",
    ),
    STORM_OF_ARMADYL(
        uniqueId = 7699,
        componentId = 99,
        maxHit = 16,
        castGfx = Graphic(457, 0),
        castAnimation = arrayOf(10546, 10546),
        projectile = 1019,
        impactGfx = Graphic(1019, 0),
        autoCastId = 145,
        experience = 70.0,
    ),

    /**
     * Ancient Magicks (interface 193).
     *
     * Animation/graphic/projectile ids from the 2009scape IceSpells/BloodSpells/ShadowSpells/
     * SmokeSpells/MiasmicSpells handlers (same ids as rev 667), autocast ids from Matrix 718
     * CombatDefinitions.getSpellAutoCastConfigValue, max hits/xp from the 2011 RuneScape Wiki.
     */

    SMOKE_RUSH(
        uniqueId = 329,
        componentId = 28,
        maxHit = 15,
        castGfx = null,
        castAnimation = arrayOf(1978, 1978),
        projectile = 384,
        impactGfx = Graphic(385, 96),
        autoCastId = 63,
        experience = 30.0,
        interfaceId = 193,
        effect = SpellEffect.Poison(2),
    ),
    SHADOW_RUSH(
        uniqueId = 337,
        componentId = 32,
        maxHit = 16,
        castGfx = null,
        castAnimation = arrayOf(1978, 1978),
        projectile = 378,
        impactGfx = Graphic(379, 96),
        autoCastId = 65,
        experience = 31.0,
        interfaceId = 193,
        effect = SpellEffect.ShadowDrain,
    ),
    BLOOD_RUSH(
        uniqueId = 333,
        componentId = 24,
        maxHit = 17,
        castGfx = null,
        castAnimation = arrayOf(1978, 1978),
        projectile = 372,
        impactGfx = Graphic(373, 96),
        autoCastId = 67,
        experience = 33.0,
        interfaceId = 193,
        effect = SpellEffect.BloodHeal,
    ),
    ICE_RUSH(
        uniqueId = 325,
        componentId = 20,
        maxHit = 18,
        castGfx = null,
        castAnimation = arrayOf(1978, 1978),
        projectile = 360,
        impactGfx = Graphic(361, 96),
        autoCastId = 69,
        experience = 34.0,
        interfaceId = 193,
        effect = SpellEffect.Freeze(8),
    ),
    SMOKE_BURST(
        uniqueId = 330,
        componentId = 30,
        maxHit = 19,
        castGfx = null,
        castAnimation = arrayOf(1979, 1979),
        projectile = 386,
        impactGfx = Graphic(387, 0),
        autoCastId = 71,
        experience = 36.0,
        interfaceId = 193,
        multiTarget = true,
        effect = SpellEffect.Poison(2),
    ),
    SHADOW_BURST(
        uniqueId = 338,
        componentId = 34,
        maxHit = 20,
        castGfx = null,
        castAnimation = arrayOf(1979, 1979),
        projectile = 380,
        impactGfx = Graphic(381, 0),
        autoCastId = 73,
        experience = 37.0,
        interfaceId = 193,
        multiTarget = true,
        effect = SpellEffect.ShadowDrain,
    ),
    BLOOD_BURST(
        uniqueId = 334,
        componentId = 26,
        maxHit = 21,
        castGfx = null,
        castAnimation = arrayOf(1979, 1979),
        projectile = -1,
        impactGfx = Graphic(376, 0),
        autoCastId = 75,
        experience = 39.0,
        interfaceId = 193,
        multiTarget = true,
        effect = SpellEffect.BloodHeal,
        fixedHitDelay = 2,
    ),
    ICE_BURST(
        uniqueId = 326,
        componentId = 22,
        maxHit = 22,
        castGfx = null,
        castAnimation = arrayOf(1979, 1979),
        projectile = 362,
        impactGfx = Graphic(363, 0),
        autoCastId = 77,
        experience = 40.0,
        interfaceId = 193,
        multiTarget = true,
        effect = SpellEffect.Freeze(16),
    ),
    SMOKE_BLITZ(
        uniqueId = 331,
        componentId = 29,
        maxHit = 23,
        castGfx = null,
        castAnimation = arrayOf(1978, 1978),
        projectile = 389,
        impactGfx = Graphic(388, 96),
        autoCastId = 79,
        experience = 42.0,
        interfaceId = 193,
        effect = SpellEffect.Poison(4),
    ),
    SHADOW_BLITZ(
        uniqueId = 339,
        componentId = 33,
        maxHit = 24,
        castGfx = null,
        castAnimation = arrayOf(1978, 1978),
        projectile = -1,
        impactGfx = Graphic(382, 96),
        autoCastId = 81,
        experience = 43.0,
        interfaceId = 193,
        effect = SpellEffect.ShadowDrain,
        fixedHitDelay = 2,
    ),
    BLOOD_BLITZ(
        uniqueId = 335,
        componentId = 25,
        maxHit = 25,
        castGfx = null,
        castAnimation = arrayOf(1978, 1978),
        projectile = 374,
        impactGfx = Graphic(375, 96),
        autoCastId = 83,
        experience = 45.0,
        interfaceId = 193,
        effect = SpellEffect.BloodHeal,
    ),
    ICE_BLITZ(
        uniqueId = 327,
        componentId = 21,
        maxHit = 26,
        castGfx = Graphic(366, 96),
        castAnimation = arrayOf(1978, 1978),
        projectile = -1,
        impactGfx = Graphic(367, 96),
        autoCastId = 85,
        experience = 46.0,
        interfaceId = 193,
        effect = SpellEffect.Freeze(24),
        fixedHitDelay = 2,
    ),
    SMOKE_BARRAGE(
        uniqueId = 332,
        componentId = 31,
        maxHit = 27,
        castGfx = null,
        castAnimation = arrayOf(1979, 1979),
        projectile = 391,
        impactGfx = Graphic(390, 0),
        autoCastId = 87,
        experience = 48.0,
        interfaceId = 193,
        multiTarget = true,
        effect = SpellEffect.Poison(4),
    ),
    SHADOW_BARRAGE(
        uniqueId = 340,
        componentId = 35,
        maxHit = 28,
        castGfx = null,
        castAnimation = arrayOf(1979, 1979),
        projectile = -1,
        impactGfx = Graphic(383, 0),
        autoCastId = 89,
        experience = 49.0,
        interfaceId = 193,
        multiTarget = true,
        effect = SpellEffect.ShadowDrain,
        fixedHitDelay = 2,
    ),
    BLOOD_BARRAGE(
        uniqueId = 336,
        componentId = 27,
        maxHit = 29,
        castGfx = null,
        castAnimation = arrayOf(1979, 1979),
        projectile = -1,
        impactGfx = Graphic(377, 0),
        autoCastId = 91,
        experience = 51.0,
        interfaceId = 193,
        multiTarget = true,
        effect = SpellEffect.BloodHeal,
        fixedHitDelay = 2,
    ),
    ICE_BARRAGE(
        uniqueId = 328,
        componentId = 23,
        maxHit = 30,
        castGfx = null,
        castAnimation = arrayOf(1979, 1979),
        projectile = 368,
        impactGfx = Graphic(369, 0),
        autoCastId = 93,
        experience = 52.0,
        interfaceId = 193,
        multiTarget = true,
        effect = SpellEffect.Freeze(32),
    ),
    MIASMIC_RUSH(
        uniqueId = 1568,
        componentId = 36,
        maxHit = 20,
        castGfx = Graphic(1845, 0),
        castAnimation = arrayOf(10513, 10513),
        projectile = 1846,
        impactGfx = Graphic(1847, 40),
        autoCastId = 95,
        experience = 36.0,
        interfaceId = 193,
        effect = SpellEffect.Miasmic(20),
        requiredWeapons = ZURIELS_STAVES,
        requiredWeaponMessage = ZURIELS_MESSAGE,
    ),
    MIASMIC_BURST(
        uniqueId = 1569,
        componentId = 38,
        maxHit = 24,
        castGfx = Graphic(1848, 0),
        castAnimation = arrayOf(10516, 10516),
        projectile = -1,
        impactGfx = Graphic(1849, 20),
        autoCastId = 97,
        experience = 42.0,
        interfaceId = 193,
        multiTarget = true,
        effect = SpellEffect.Miasmic(40),
        requiredWeapons = ZURIELS_STAVES,
        requiredWeaponMessage = ZURIELS_MESSAGE,
        fixedHitDelay = 2,
    ),
    MIASMIC_BLITZ(
        uniqueId = 1567,
        componentId = 37,
        maxHit = 28,
        castGfx = Graphic(1850, 15),
        castAnimation = arrayOf(10524, 10524),
        projectile = 1852,
        impactGfx = Graphic(1851, 0),
        autoCastId = 99,
        experience = 48.0,
        interfaceId = 193,
        effect = SpellEffect.Miasmic(60),
        requiredWeapons = ZURIELS_STAVES,
        requiredWeaponMessage = ZURIELS_MESSAGE,
    ),
    MIASMIC_BARRAGE(
        uniqueId = 1566,
        componentId = 39,
        maxHit = 32,
        castGfx = Graphic(1853, 0),
        castAnimation = arrayOf(10518, 10518),
        projectile = -1,
        impactGfx = Graphic(1854, 0),
        autoCastId = 101,
        experience = 54.0,
        interfaceId = 193,
        multiTarget = true,
        effect = SpellEffect.Miasmic(80),
        requiredWeapons = ZURIELS_STAVES,
        requiredWeaponMessage = ZURIELS_MESSAGE,
        fixedHitDelay = 2,
    ),

    /**
     * NPC Spells
     */

    WEAK_FIRE_BLAST(
        uniqueId = 995,
        componentId = -1,
        maxHit = 8,
        castGfx = Graphic(Gfx.FIRE_SPELL_CAST, 22),
        castAnimation = arrayOf(Anims.FIRE_SPELL, Anims.FIRE_SPELL_WITH_STAFF),
        projectile = Gfx.FIRE_BLAST_PROJ,
        secondProjectile = Gfx.FIRE_BLAST_PROJ_2,
        impactGfx = Graphic(Gfx.FIRE_BLAST_IMPACT, 32),
        autoCastId = -1,
        experience = 0.0,
    ),
    WARLOCK_SKELETON_EARTH_STRIKE(
        uniqueId = 996,
        componentId = -1,
        maxHit = 6,
        castGfx = Graphic(Gfx.EARTH_SPELL_CAST, -4),
        castAnimation = arrayOf(Anims.WARLOCK_WEAK_EARTH_STRIKE),
        projectile = Gfx.EARTH_STRIKE_PROJ,
        impactGfx = Graphic(Gfx.EARTH_STRIKE_IMPACT, 60),
        autoCastId = 7,
        experience = 9.5,
    ),

    ;

    companion object {
        val values = enumValues<CombatSpell>()

        /** Spells keyed by (interfaceId shl 16 or componentId) so Ancient component ids never collide with the standard book. */
        val definitions = CombatSpell.values().filter { it.componentId != -1 }.associateBy { (it.interfaceId shl 16) or it.componentId }

        fun forComponent(interfaceId: Int, componentId: Int): CombatSpell? = definitions[(interfaceId shl 16) or componentId]
    }
}
