package gg.rsmod.plugins.content.magic

import gg.rsmod.game.model.item.Item
import gg.rsmod.plugins.api.cfg.Items
import gg.rsmod.plugins.api.cfg.Sfx

enum class SpellbookData(
    val interfaceId: Int,
    val component: Int,
    val uniqueId: Int,
    val spellType: SpellType,
    val spellName: String,
    val level: Int,
    val runes: List<Item> = emptyList(),
    val sound: Int,
    val hitSound: Int,
) {
    HOME_TELEPORT(
        interfaceId = 192,
        component = 24,
        uniqueId = 356,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Home Teleport",
        level = 1,
        sound = -1,
        hitSound = -1,
    ),
    WIND_RUSH(
        interfaceId = 192,
        component = 98,
        uniqueId = 3759,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Wind Rush",
        level = 1,
        runes = listOf(Item(Items.AIR_RUNE, 2)),
        sound = Sfx.WINDSTRIKE_CAST_AND_FIRE,
        hitSound = Sfx.WINDSTRIKE_HIT,
    ),
    WIND_STRIKE(
        interfaceId = 192,
        component = 25,
        uniqueId = 15,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Wind Strike",
        level = 1,
        runes = listOf(Item(Items.AIR_RUNE, 1), Item(Items.MIND_RUNE, 1)),
        sound = Sfx.WINDSTRIKE_CAST_AND_FIRE,
        hitSound = Sfx.WINDSTRIKE_HIT,
    ),
    WATER_STRIKE(
        interfaceId = 192,
        component = 28,
        uniqueId = 17,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Water Strike",
        level = 5,
        runes = listOf(Item(Items.AIR_RUNE, 1), Item(Items.MIND_RUNE, 1), Item(Items.WATER_RUNE, 1)),
        sound = Sfx.WATERSTRIKE_CAST_AND_FIRE,
        hitSound = Sfx.WATERSTRIKE_HIT,
    ),
    LVL_1_ENCHANT(
        interfaceId = 192,
        component = 29,
        uniqueId = 18,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Lvl-1 Enchant",
        level = 7,
        runes = listOf(Item(Items.COSMIC_RUNE, 1), Item(Items.WATER_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    EARTH_STRIKE(
        interfaceId = 192,
        component = 30,
        uniqueId = 19,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Earth Strike",
        level = 9,
        runes = listOf(Item(Items.AIR_RUNE, 1), Item(Items.MIND_RUNE, 1), Item(Items.EARTH_RUNE, 2)),
        sound = Sfx.EARTHSTRIKE_CAST_AND_FIRE,
        hitSound = Sfx.EARTHSTRIKE_HIT,
    ),
    MOBILISING_ARMIES(
        interfaceId = 192,
        component = 37,
        uniqueId = 1564,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Mobilising Armies Teleport",
        level = 10,
        runes = listOf(Item(Items.WATER_RUNE), Item(Items.AIR_RUNE, 3), Item(Items.LAW_RUNE)),
        sound = -1,
        hitSound = -1,
    ),
    FIRE_STRIKE(
        interfaceId = 192,
        component = 32,
        uniqueId = 71,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Fire Strike",
        level = 13,
        runes = listOf(Item(Items.AIR_RUNE, 1), Item(Items.MIND_RUNE, 1), Item(Items.FIRE_RUNE, 3)),
        sound = Sfx.FIRESTRIKE_CAST_AND_FIRE,
        hitSound = Sfx.FIRESTRIKE_HIT,
    ),
    WIND_BOLT(
        interfaceId = 192,
        component = 34,
        uniqueId = 73,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Wind Bolt",
        level = 17,
        runes = listOf(Item(Items.AIR_RUNE, 2), Item(Items.CHAOS_RUNE, 1)),
        sound = Sfx.WINDBOLT_CAST_AND_FIRE,
        hitSound = Sfx.WINDBOLT_HIT,
    ),
    LOW_ALCHEMY(
        interfaceId = 192,
        component = 38,
        uniqueId = 75,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Low Alchemy",
        level = 21,
        runes = listOf(Item(Items.FIRE_RUNE, 3), Item(Items.NATURE_RUNE, 1)),
        sound = Sfx.LOW_ALCHEMY,
        hitSound = -1,
    ),
    WATER_BOLT(
        interfaceId = 192,
        component = 39,
        uniqueId = 76,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Water Bolt",
        level = 23,
        runes = listOf(Item(Items.AIR_RUNE, 2), Item(Items.WATER_RUNE, 2), Item(Items.CHAOS_RUNE, 1)),
        sound = Sfx.WATERBOLT_CAST_AND_FIRE,
        hitSound = Sfx.WATERBOLT_HIT,
    ),
    VARROCK_TELEPORT(
        interfaceId = 192,
        component = 40,
        uniqueId = 77,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Varrock Teleport",
        level = 25,
        runes = listOf(Item(Items.FIRE_RUNE), Item(Items.AIR_RUNE, 3), Item(Items.LAW_RUNE)),
        sound = -1,
        hitSound = -1,
    ),
    LVL_2_ENCHANT(
        interfaceId = 192,
        component = 41,
        uniqueId = 78,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Lvl-2 Enchant",
        level = 27,
        runes = listOf(Item(Items.COSMIC_RUNE, 1), Item(Items.AIR_RUNE, 3)),
        sound = -1,
        hitSound = -1,
    ),
    EARTH_BOLT(
        interfaceId = 192,
        component = 42,
        uniqueId = 79,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Earth Bolt",
        level = 29,
        runes = listOf(Item(Items.AIR_RUNE, 2), Item(Items.EARTH_RUNE, 3), Item(Items.CHAOS_RUNE, 1)),
        sound = Sfx.EARTHBOLT_CAST_AND_FIRE,
        hitSound = Sfx.EARTHBOLT_HIT,
    ),
    LUMBRIDGE_TELEPORT(
        interfaceId = 192,
        component = 43,
        uniqueId = 80,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Lumbridge Teleport",
        level = 31,
        runes = listOf(Item(Items.EARTH_RUNE), Item(Items.AIR_RUNE, 3), Item(Items.LAW_RUNE)),
        sound = -1,
        hitSound = -1,
    ),
    TELEKINETIC_GRAB(
        interfaceId = 192,
        component = 44,
        uniqueId = 81,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Telekinetic Grab",
        level = 33,
        runes = listOf(Item(Items.AIR_RUNE), Item(Items.LAW_RUNE)),
        sound = Sfx.TELEGRAB_CAST_AND_FIRE,
        hitSound = Sfx.TELEGRAB_HIT,
    ),
    FIRE_BOLT(
        interfaceId = 192,
        component = 45,
        uniqueId = 82,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Fire Bolt",
        level = 35,
        runes = listOf(Item(Items.AIR_RUNE, 3), Item(Items.FIRE_RUNE, 4), Item(Items.CHAOS_RUNE, 1)),
        sound = Sfx.FIREBOLT_CAST_AND_FIRE,
        hitSound = Sfx.FIREBOLT_HIT,
    ),
    FALADOR_TELEPORT(
        interfaceId = 192,
        component = 46,
        uniqueId = 83,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Falador Teleport",
        level = 37,
        runes = listOf(Item(Items.WATER_RUNE), Item(Items.AIR_RUNE, 3), Item(Items.LAW_RUNE)),
        sound = -1,
        hitSound = -1,
    ),
    WIND_BLAST(
        interfaceId = 192,
        component = 49,
        uniqueId = 85,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Wind Blast",
        level = 41,
        runes = listOf(Item(Items.AIR_RUNE, 3), Item(Items.DEATH_RUNE, 1)),
        sound = Sfx.WINDBLAST_CAST_AND_FIRE,
        hitSound = Sfx.WINDBLAST_HIT,
    ),
    SUPERHEAT_ITEM(
        interfaceId = 192,
        component = 50,
        uniqueId = 86,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Superheat Item",
        level = 43,
        runes = listOf(Item(Items.FIRE_RUNE, 4), Item(Items.NATURE_RUNE, 1)),
        sound = Sfx.SUPERHEAT_ALL,
        hitSound = -1,
    ),
    CAMELOT_TELEPORT(
        interfaceId = 192,
        component = 51,
        uniqueId = 87,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Camelot Teleport",
        level = 45,
        runes = listOf(Item(Items.AIR_RUNE, 5), Item(Items.LAW_RUNE)),
        sound = -1,
        hitSound = -1,
    ),
    WATER_BLAST(
        interfaceId = 192,
        component = 52,
        uniqueId = 88,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Water Blast",
        level = 47,
        runes = listOf(Item(Items.AIR_RUNE, 3), Item(Items.WATER_RUNE, 3), Item(Items.DEATH_RUNE, 1)),
        sound = Sfx.WATERBLAST_CAST_AND_FIRE,
        hitSound = Sfx.WATERBLAST_HIT,
    ),
    LVL_3_ENCHANT(
        interfaceId = 192,
        component = 53,
        uniqueId = 89,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Lvl-3 Enchant",
        level = 49,
        runes = listOf(Item(Items.COSMIC_RUNE, 1), Item(Items.FIRE_RUNE, 5)),
        sound = -1,
        hitSound = -1,
    ),
    ARDOUGNE_TELEPORT(
        interfaceId = 192,
        component = 57,
        uniqueId = 104,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Ardougne Teleport",
        level = 51,
        runes = listOf(Item(Items.WATER_RUNE, 2), Item(Items.LAW_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    EARTH_BLAST(
        interfaceId = 192,
        component = 58,
        uniqueId = 90,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Earth Blast",
        level = 53,
        runes = listOf(Item(Items.AIR_RUNE, 3), Item(Items.EARTH_RUNE, 4), Item(Items.DEATH_RUNE, 1)),
        sound = Sfx.EARTHBLAST_CAST_AND_FIRE,
        hitSound = Sfx.EARTHBLAST_HIT,
    ),
    HIGH_ALCHEMY(
        interfaceId = 192,
        component = 59,
        uniqueId = 91,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "High Alchemy",
        level = 55,
        runes = listOf(Item(Items.FIRE_RUNE, 5), Item(Items.NATURE_RUNE, 1)),
        sound = Sfx.HIGH_ALCHEMY,
        hitSound = -1,
    ),
    LVL_4_ENCHANT(
        interfaceId = 192,
        component = 61,
        uniqueId = 93,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Lvl-4 Enchant",
        level = 57,
        runes = listOf(Item(Items.COSMIC_RUNE, 1), Item(Items.EARTH_RUNE, 10)),
        sound = -1,
        hitSound = -1,
    ),
    WATCHTOWER_TELEPORT(
        interfaceId = 192,
        component = 62,
        uniqueId = 105,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Watchtower Teleport",
        level = 58,
        runes = listOf(Item(Items.EARTH_RUNE, 2), Item(Items.LAW_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    FIRE_BLAST(
        interfaceId = 192,
        component = 63,
        uniqueId = 95,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Fire Blast",
        level = 59,
        runes = listOf(Item(Items.AIR_RUNE, 4), Item(Items.FIRE_RUNE, 5), Item(Items.DEATH_RUNE, 1)),
        sound = Sfx.FIREBLAST_CAST_AND_FIRE,
        hitSound = Sfx.FIREBLAST_HIT,
    ),
    SARADOMIN_STRIKE(
        interfaceId = 192,
        component = 66,
        uniqueId = 501,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Saradomin Strike",
        level = 60,
        runes = listOf(Item(Items.FIRE_RUNE, 2), Item(Items.BLOOD_RUNE, 2), Item(Items.AIR_RUNE, 4)),
        sound = Sfx.SARADOMIN_STRIKE,
        hitSound = -1,
    ),
    CLAWS_OF_GUTHIX(
        interfaceId = 192,
        component = 67,
        uniqueId = 502,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Claws of Guthix",
        level = 60,
        runes = listOf(Item(Items.FIRE_RUNE, 1), Item(Items.BLOOD_RUNE, 2), Item(Items.AIR_RUNE, 4)),
        sound = Sfx.CLAWS_OF_GUTHIX,
        hitSound = -1,
    ),
    FLAMES_OF_ZAMORAK(
        interfaceId = 192,
        component = 68,
        uniqueId = 503,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Flames of Zamorak",
        level = 60,
        runes = listOf(Item(Items.FIRE_RUNE, 4), Item(Items.BLOOD_RUNE, 2), Item(Items.AIR_RUNE, 1)),
        sound = Sfx.FLAMES_OF_ZAMORAK,
        hitSound = -1,
    ),
    TROLLHEIM_TELEPORT(
        interfaceId = 192,
        component = 69,
        uniqueId = 373,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Trollheim Teleport",
        level = 61,
        runes = listOf(Item(Items.FIRE_RUNE, 2), Item(Items.LAW_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    WIND_WAVE(
        interfaceId = 192,
        component = 70,
        uniqueId = 96,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Wind Wave",
        level = 62,
        runes = listOf(Item(Items.AIR_RUNE, 5), Item(Items.BLOOD_RUNE, 1)),
        sound = Sfx.WINDWAVE_CAST_AND_FIRE,
        hitSound = Sfx.WINDWAVE_HIT,
    ),
    APE_ATOLL_TELEPORT(
        interfaceId = 192,
        component = 72,
        uniqueId = 407,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Teleport to Ape Atoll",
        level = 64,
        runes =
            listOf(
                Item(Items.FIRE_RUNE, 2),
                Item(Items.WATER_RUNE, 2),
                Item(Items.LAW_RUNE, 2),
                Item(Items.BANANA),
            ),
        sound = -1,
        hitSound = -1,
    ),
    WATER_WAVE(
        interfaceId = 192,
        component = 73,
        uniqueId = 98,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Water Wave",
        level = 65,
        runes = listOf(Item(Items.AIR_RUNE, 5), Item(Items.WATER_RUNE, 7), Item(Items.BLOOD_RUNE, 1)),
        sound = Sfx.WATERWAVE_CAST_AND_FIRE,
        hitSound = Sfx.WATERWAVE_HIT,
    ),
    LVL_5_ENCHANT(
        interfaceId = 192,
        component = 76,
        uniqueId = 100,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Lvl-5 Enchant",
        level = 68,
        runes = listOf(Item(Items.COSMIC_RUNE, 1), Item(Items.EARTH_RUNE, 15), Item(Items.WATER_RUNE, 15)),
        sound = -1,
        hitSound = -1,
    ),
    EARTH_WAVE(
        interfaceId = 192,
        component = 77,
        uniqueId = 101,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Earth Wave",
        level = 70,
        runes = listOf(Item(Items.AIR_RUNE, 5), Item(Items.EARTH_RUNE, 7), Item(Items.BLOOD_RUNE, 1)),
        sound = Sfx.EARTHWAVE_CAST_AND_FIRE,
        hitSound = Sfx.EARTHWAVE_HIT,
    ),
    FIRE_WAVE(
        interfaceId = 192,
        component = 80,
        uniqueId = 102,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Fire Wave",
        level = 75,
        runes = listOf(Item(Items.AIR_RUNE, 5), Item(Items.FIRE_RUNE, 7), Item(Items.BLOOD_RUNE, 1)),
        sound = Sfx.FIREWAVE_CAST_AND_FIRE,
        hitSound = Sfx.FIREWAVE_HIT,
    ),
    WIND_SURGE(
        interfaceId = 192,
        component = 84,
        uniqueId = 815,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Wind Surge",
        level = 81,
        runes = listOf(Item(Items.AIR_RUNE, 7), Item(Items.DEATH_RUNE, 1), Item(Items.BLOOD_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    WATER_SURGE(
        interfaceId = 192,
        component = 87,
        uniqueId = 816,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Water Surge",
        level = 85,
        runes =
            listOf(
                Item(Items.AIR_RUNE, 7),
                Item(Items.WATER_RUNE, 10),
                Item(Items.DEATH_RUNE, 1),
                Item(Items.BLOOD_RUNE, 1),
            ),
        sound = -1,
        hitSound = -1,
    ),
    LVL_6_ENCHANT(
        interfaceId = 192,
        component = 88,
        uniqueId = 403,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Lvl-6 Enchant",
        level = 87,
        runes = listOf(Item(Items.COSMIC_RUNE, 1), Item(Items.EARTH_RUNE, 20), Item(Items.FIRE_RUNE, 20)),
        sound = -1,
        hitSound = -1,
    ),
    EARTH_SURGE(
        interfaceId = 192,
        component = 89,
        uniqueId = 817,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Earth Surge",
        level = 90,
        runes =
            listOf(
                Item(Items.AIR_RUNE, 7),
                Item(Items.EARTH_RUNE, 10),
                Item(Items.DEATH_RUNE, 1),
                Item(Items.BLOOD_RUNE, 1),
            ),
        sound = -1,
        hitSound = -1,
    ),
    FIRE_SURGE(
        interfaceId = 192,
        component = 91,
        uniqueId = 818,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Fire Surge",
        level = 95,
        runes =
            listOf(
                Item(Items.AIR_RUNE, 7),
                Item(Items.FIRE_RUNE, 10),
                Item(Items.DEATH_RUNE, 1),
                Item(Items.BLOOD_RUNE, 1),
            ),
        sound = -1,
        hitSound = -1,
    ),

    /*
     * Standard spellbook (interface 192): remaining spells. Levels and runes decoded from the
     * interface component onLoad hooks in the production cache (InterfaceHookProbeTool).
     */
    CONFUSE(
        interfaceId = 192,
        component = 26,
        uniqueId = 16,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Confuse",
        level = 3,
        runes = listOf(Item(Items.WATER_RUNE, 3), Item(Items.EARTH_RUNE, 2), Item(Items.BODY_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    ENCHANT_CROSSBOW_BOLT(
        interfaceId = 192,
        component = 27,
        uniqueId = 358,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Enchant Crossbow Bolt",
        level = 4,
        sound = -1,
        hitSound = -1,
    ),
    WEAKEN(
        interfaceId = 192,
        component = 31,
        uniqueId = 20,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Weaken",
        level = 11,
        runes = listOf(Item(Items.WATER_RUNE, 3), Item(Items.EARTH_RUNE, 2), Item(Items.BODY_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    BONES_TO_BANANAS(
        interfaceId = 192,
        component = 33,
        uniqueId = 22,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Bones to Bananas",
        level = 15,
        runes = listOf(Item(Items.EARTH_RUNE, 2), Item(Items.WATER_RUNE, 2), Item(Items.NATURE_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    CURSE(
        interfaceId = 192,
        component = 35,
        uniqueId = 24,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Curse",
        level = 19,
        runes = listOf(Item(Items.WATER_RUNE, 2), Item(Items.EARTH_RUNE, 3), Item(Items.BODY_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    BIND(
        interfaceId = 192,
        component = 36,
        uniqueId = 319,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Bind",
        level = 20,
        runes = listOf(Item(Items.EARTH_RUNE, 3), Item(Items.WATER_RUNE, 3), Item(Items.NATURE_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    CRUMBLE_UNDEAD(
        interfaceId = 192,
        component = 47,
        uniqueId = 34,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Crumble Undead",
        level = 39,
        runes = listOf(Item(Items.EARTH_RUNE, 2), Item(Items.AIR_RUNE, 2), Item(Items.CHAOS_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    TELEPORT_TO_HOUSE(
        interfaceId = 192,
        component = 48,
        uniqueId = 355,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Teleport to House",
        level = 40,
        runes = listOf(Item(Items.LAW_RUNE, 1), Item(Items.AIR_RUNE, 1), Item(Items.EARTH_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    IBAN_BLAST(
        interfaceId = 192,
        component = 54,
        uniqueId = 53,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Iban Blast",
        level = 50,
        runes = listOf(Item(Items.FIRE_RUNE, 5), Item(Items.DEATH_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    SNARE(
        interfaceId = 192,
        component = 55,
        uniqueId = 320,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Snare",
        level = 50,
        runes = listOf(Item(Items.EARTH_RUNE, 4), Item(Items.WATER_RUNE, 4), Item(Items.NATURE_RUNE, 3)),
        sound = -1,
        hitSound = -1,
    ),
    MAGIC_DART(
        interfaceId = 192,
        component = 56,
        uniqueId = 324,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Magic Dart",
        level = 50,
        runes = listOf(Item(Items.DEATH_RUNE, 1), Item(Items.MIND_RUNE, 4)),
        sound = -1,
        hitSound = -1,
    ),
    CHARGE_WATER_ORB(
        interfaceId = 192,
        component = 60,
        uniqueId = 42,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Charge Water Orb",
        level = 56,
        runes = listOf(Item(Items.WATER_RUNE, 30), Item(Items.COSMIC_RUNE, 3), Item(Items.UNPOWERED_ORB, 1)),
        sound = -1,
        hitSound = -1,
    ),
    CHARGE_EARTH_ORB(
        interfaceId = 192,
        component = 64,
        uniqueId = 45,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Charge Earth Orb",
        level = 60,
        runes = listOf(Item(Items.EARTH_RUNE, 30), Item(Items.COSMIC_RUNE, 3), Item(Items.UNPOWERED_ORB, 1)),
        sound = -1,
        hitSound = -1,
    ),
    BONES_TO_PEACHES(
        interfaceId = 192,
        component = 65,
        uniqueId = 354,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Bones to Peaches",
        level = 60,
        runes = listOf(Item(Items.NATURE_RUNE, 2), Item(Items.WATER_RUNE, 4), Item(Items.EARTH_RUNE, 4)),
        sound = -1,
        hitSound = -1,
    ),
    CHARGE_FIRE_ORB(
        interfaceId = 192,
        component = 71,
        uniqueId = 47,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Charge Fire Orb",
        level = 63,
        runes = listOf(Item(Items.FIRE_RUNE, 30), Item(Items.COSMIC_RUNE, 3), Item(Items.UNPOWERED_ORB, 1)),
        sound = -1,
        hitSound = -1,
    ),
    CHARGE_AIR_ORB(
        interfaceId = 192,
        component = 74,
        uniqueId = 49,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Charge Air Orb",
        level = 66,
        runes = listOf(Item(Items.AIR_RUNE, 30), Item(Items.COSMIC_RUNE, 3), Item(Items.UNPOWERED_ORB, 1)),
        sound = -1,
        hitSound = -1,
    ),
    VULNERABILITY(
        interfaceId = 192,
        component = 75,
        uniqueId = 56,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Vulnerability",
        level = 66,
        runes = listOf(Item(Items.EARTH_RUNE, 5), Item(Items.WATER_RUNE, 5), Item(Items.SOUL_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    ENFEEBLE(
        interfaceId = 192,
        component = 78,
        uniqueId = 57,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Enfeeble",
        level = 73,
        runes = listOf(Item(Items.EARTH_RUNE, 8), Item(Items.WATER_RUNE, 8), Item(Items.SOUL_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    TELEOTHER_LUMBRIDGE(
        interfaceId = 192,
        component = 79,
        uniqueId = 349,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Teleother Lumbridge",
        level = 74,
        runes = listOf(Item(Items.SOUL_RUNE, 1), Item(Items.LAW_RUNE, 1), Item(Items.EARTH_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    ENTANGLE(
        interfaceId = 192,
        component = 81,
        uniqueId = 321,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Entangle",
        level = 79,
        runes = listOf(Item(Items.EARTH_RUNE, 5), Item(Items.WATER_RUNE, 5), Item(Items.NATURE_RUNE, 4)),
        sound = -1,
        hitSound = -1,
    ),
    STUN(
        interfaceId = 192,
        component = 82,
        uniqueId = 58,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Stun",
        level = 80,
        runes = listOf(Item(Items.EARTH_RUNE, 12), Item(Items.WATER_RUNE, 12), Item(Items.SOUL_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    CHARGE(
        interfaceId = 192,
        component = 83,
        uniqueId = 322,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Charge",
        level = 80,
        runes = listOf(Item(Items.FIRE_RUNE, 3), Item(Items.BLOOD_RUNE, 3), Item(Items.AIR_RUNE, 3)),
        sound = -1,
        hitSound = -1,
    ),
    TELEOTHER_FALADOR(
        interfaceId = 192,
        component = 85,
        uniqueId = 350,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Teleother Falador",
        level = 82,
        runes = listOf(Item(Items.SOUL_RUNE, 1), Item(Items.WATER_RUNE, 1), Item(Items.LAW_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    TELEPORT_BLOCK(
        interfaceId = 192,
        component = 86,
        uniqueId = 1565,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Teleport Block",
        level = 85,
        runes = listOf(Item(Items.CHAOS_RUNE, 1), Item(Items.LAW_RUNE, 1), Item(Items.DEATH_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    TELEOTHER_CAMELOT(
        interfaceId = 192,
        component = 90,
        uniqueId = 351,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Teleother Camelot",
        level = 90,
        runes = listOf(Item(Items.SOUL_RUNE, 2), Item(Items.LAW_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    STORM_OF_ARMADYL(
        interfaceId = 192,
        component = 99,
        uniqueId = 7699,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Storm of Armadyl",
        level = 77,
        runes = listOf(Item(Items.ARMADYL_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),

    /*
     * Ancient Magicks (interface 193). Decoded from the production cache.
     */
    ICE_RUSH(
        interfaceId = 193,
        component = 20,
        uniqueId = 325,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Ice Rush",
        level = 58,
        runes = listOf(Item(Items.CHAOS_RUNE, 2), Item(Items.DEATH_RUNE, 2), Item(Items.WATER_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    ICE_BLITZ(
        interfaceId = 193,
        component = 21,
        uniqueId = 327,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Ice Blitz",
        level = 82,
        runes = listOf(Item(Items.DEATH_RUNE, 2), Item(Items.BLOOD_RUNE, 2), Item(Items.WATER_RUNE, 3)),
        sound = -1,
        hitSound = -1,
    ),
    ICE_BURST(
        interfaceId = 193,
        component = 22,
        uniqueId = 326,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Ice Burst",
        level = 70,
        runes = listOf(Item(Items.CHAOS_RUNE, 4), Item(Items.DEATH_RUNE, 2), Item(Items.WATER_RUNE, 4)),
        sound = -1,
        hitSound = -1,
    ),
    ICE_BARRAGE(
        interfaceId = 193,
        component = 23,
        uniqueId = 328,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Ice Barrage",
        level = 94,
        runes = listOf(Item(Items.DEATH_RUNE, 4), Item(Items.BLOOD_RUNE, 2), Item(Items.WATER_RUNE, 6)),
        sound = -1,
        hitSound = -1,
    ),
    BLOOD_RUSH(
        interfaceId = 193,
        component = 24,
        uniqueId = 333,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Blood Rush",
        level = 56,
        runes = listOf(Item(Items.CHAOS_RUNE, 2), Item(Items.DEATH_RUNE, 2), Item(Items.BLOOD_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    BLOOD_BLITZ(
        interfaceId = 193,
        component = 25,
        uniqueId = 335,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Blood Blitz",
        level = 80,
        runes = listOf(Item(Items.DEATH_RUNE, 2), Item(Items.BLOOD_RUNE, 4)),
        sound = -1,
        hitSound = -1,
    ),
    BLOOD_BURST(
        interfaceId = 193,
        component = 26,
        uniqueId = 334,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Blood Burst",
        level = 68,
        runes = listOf(Item(Items.CHAOS_RUNE, 4), Item(Items.DEATH_RUNE, 2), Item(Items.BLOOD_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    BLOOD_BARRAGE(
        interfaceId = 193,
        component = 27,
        uniqueId = 336,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Blood Barrage",
        level = 92,
        runes = listOf(Item(Items.DEATH_RUNE, 4), Item(Items.BLOOD_RUNE, 4), Item(Items.SOUL_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    SMOKE_RUSH(
        interfaceId = 193,
        component = 28,
        uniqueId = 329,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Smoke Rush",
        level = 50,
        runes = listOf(Item(Items.CHAOS_RUNE, 2), Item(Items.DEATH_RUNE, 2), Item(Items.FIRE_RUNE, 1), Item(Items.AIR_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    SMOKE_BLITZ(
        interfaceId = 193,
        component = 29,
        uniqueId = 331,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Smoke Blitz",
        level = 74,
        runes = listOf(Item(Items.DEATH_RUNE, 2), Item(Items.BLOOD_RUNE, 2), Item(Items.FIRE_RUNE, 2), Item(Items.AIR_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    SMOKE_BURST(
        interfaceId = 193,
        component = 30,
        uniqueId = 330,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Smoke Burst",
        level = 62,
        runes = listOf(Item(Items.CHAOS_RUNE, 4), Item(Items.DEATH_RUNE, 2), Item(Items.FIRE_RUNE, 2), Item(Items.AIR_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    SMOKE_BARRAGE(
        interfaceId = 193,
        component = 31,
        uniqueId = 332,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Smoke Barrage",
        level = 86,
        runes = listOf(Item(Items.DEATH_RUNE, 4), Item(Items.BLOOD_RUNE, 2), Item(Items.FIRE_RUNE, 4), Item(Items.AIR_RUNE, 4)),
        sound = -1,
        hitSound = -1,
    ),
    SHADOW_RUSH(
        interfaceId = 193,
        component = 32,
        uniqueId = 337,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Shadow Rush",
        level = 52,
        runes = listOf(Item(Items.CHAOS_RUNE, 2), Item(Items.DEATH_RUNE, 2), Item(Items.AIR_RUNE, 1), Item(Items.SOUL_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    SHADOW_BLITZ(
        interfaceId = 193,
        component = 33,
        uniqueId = 339,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Shadow Blitz",
        level = 76,
        runes = listOf(Item(Items.DEATH_RUNE, 2), Item(Items.BLOOD_RUNE, 2), Item(Items.AIR_RUNE, 2), Item(Items.SOUL_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    SHADOW_BURST(
        interfaceId = 193,
        component = 34,
        uniqueId = 338,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Shadow Burst",
        level = 64,
        runes = listOf(Item(Items.CHAOS_RUNE, 4), Item(Items.DEATH_RUNE, 2), Item(Items.AIR_RUNE, 1), Item(Items.SOUL_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    SHADOW_BARRAGE(
        interfaceId = 193,
        component = 35,
        uniqueId = 340,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Shadow Barrage",
        level = 88,
        runes = listOf(Item(Items.DEATH_RUNE, 4), Item(Items.BLOOD_RUNE, 2), Item(Items.AIR_RUNE, 4), Item(Items.SOUL_RUNE, 3)),
        sound = -1,
        hitSound = -1,
    ),
    MIASMIC_RUSH(
        interfaceId = 193,
        component = 36,
        uniqueId = 1568,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Miasmic Rush",
        level = 61,
        runes = listOf(Item(Items.CHAOS_RUNE, 2), Item(Items.EARTH_RUNE, 1), Item(Items.SOUL_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    MIASMIC_BLITZ(
        interfaceId = 193,
        component = 37,
        uniqueId = 1567,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Miasmic Blitz",
        level = 85,
        runes = listOf(Item(Items.BLOOD_RUNE, 2), Item(Items.EARTH_RUNE, 3), Item(Items.SOUL_RUNE, 3)),
        sound = -1,
        hitSound = -1,
    ),
    MIASMIC_BURST(
        interfaceId = 193,
        component = 38,
        uniqueId = 1569,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Miasmic Burst",
        level = 73,
        runes = listOf(Item(Items.CHAOS_RUNE, 4), Item(Items.EARTH_RUNE, 2), Item(Items.SOUL_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    MIASMIC_BARRAGE(
        interfaceId = 193,
        component = 39,
        uniqueId = 1566,
        spellType = SpellType.COMBAT_SPELL_TYPE,
        spellName = "Miasmic Barrage",
        level = 97,
        runes = listOf(Item(Items.BLOOD_RUNE, 4), Item(Items.EARTH_RUNE, 4), Item(Items.SOUL_RUNE, 4)),
        sound = -1,
        hitSound = -1,
    ),
    PADDEWWA_TELEPORT(
        interfaceId = 193,
        component = 40,
        uniqueId = 341,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Paddewwa Teleport",
        level = 54,
        runes = listOf(Item(Items.LAW_RUNE, 2), Item(Items.FIRE_RUNE, 1), Item(Items.AIR_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    SENNTISTEN_TELEPORT(
        interfaceId = 193,
        component = 41,
        uniqueId = 342,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Senntisten Teleport",
        level = 60,
        runes = listOf(Item(Items.LAW_RUNE, 2), Item(Items.SOUL_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    KHARYRLL_TELEPORT(
        interfaceId = 193,
        component = 42,
        uniqueId = 343,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Kharyrll Teleport",
        level = 66,
        runes = listOf(Item(Items.LAW_RUNE, 2), Item(Items.BLOOD_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    LASSAR_TELEPORT(
        interfaceId = 193,
        component = 43,
        uniqueId = 344,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Lassar Teleport",
        level = 72,
        runes = listOf(Item(Items.LAW_RUNE, 2), Item(Items.WATER_RUNE, 4)),
        sound = -1,
        hitSound = -1,
    ),
    DAREEYAK_TELEPORT(
        interfaceId = 193,
        component = 44,
        uniqueId = 345,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Dareeyak Teleport",
        level = 78,
        runes = listOf(Item(Items.LAW_RUNE, 2), Item(Items.FIRE_RUNE, 3), Item(Items.AIR_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    CARRALLANGAR_TELEPORT(
        interfaceId = 193,
        component = 45,
        uniqueId = 346,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Carrallangar Teleport",
        level = 84,
        runes = listOf(Item(Items.LAW_RUNE, 2), Item(Items.SOUL_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    ANNAKARL_TELEPORT(
        interfaceId = 193,
        component = 46,
        uniqueId = 347,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Annakarl Teleport",
        level = 90,
        runes = listOf(Item(Items.LAW_RUNE, 2), Item(Items.BLOOD_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    GHORROCK_TELEPORT(
        interfaceId = 193,
        component = 47,
        uniqueId = 348,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Ghorrock Teleport",
        level = 96,
        runes = listOf(Item(Items.LAW_RUNE, 2), Item(Items.WATER_RUNE, 8)),
        sound = -1,
        hitSound = -1,
    ),
    ANCIENT_HOME_TELEPORT(
        interfaceId = 193,
        component = 48,
        uniqueId = 100356,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Edgeville Home Teleport",
        level = 0,
        sound = -1,
        hitSound = -1,
    ),

    /*
     * Lunar spellbook (interface 430). Decoded from the production cache.
     */
    BARBARIAN_TELEPORT(
        interfaceId = 430,
        component = 22,
        uniqueId = 547,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Barbarian Teleport",
        level = 75,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.LAW_RUNE, 2), Item(Items.FIRE_RUNE, 3)),
        sound = -1,
        hitSound = -1,
    ),
    CURE_OTHER(
        interfaceId = 430,
        component = 23,
        uniqueId = 559,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Cure Other",
        level = 68,
        runes = listOf(Item(Items.ASTRAL_RUNE, 1), Item(Items.EARTH_RUNE, 10)),
        sound = -1,
        hitSound = -1,
    ),
    FERTILE_SOIL(
        interfaceId = 430,
        component = 24,
        uniqueId = 553,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Fertile Soil",
        level = 83,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.NATURE_RUNE, 2), Item(Items.EARTH_RUNE, 15)),
        sound = -1,
        hitSound = -1,
    ),
    CURE_GROUP(
        interfaceId = 430,
        component = 25,
        uniqueId = 565,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Cure Group",
        level = 74,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.COSMIC_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    NPC_CONTACT(
        interfaceId = 430,
        component = 26,
        uniqueId = 568,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "NPC Contact",
        level = 67,
        runes = listOf(Item(Items.ASTRAL_RUNE, 1), Item(Items.COSMIC_RUNE, 1), Item(Items.AIR_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    ENERGY_TRANSFER(
        interfaceId = 430,
        component = 27,
        uniqueId = 558,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Energy Transfer",
        level = 91,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.LAW_RUNE, 2), Item(Items.NATURE_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    MONSTER_EXAMINE(
        interfaceId = 430,
        component = 28,
        uniqueId = 577,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Monster Examine",
        level = 66,
        runes = listOf(Item(Items.ASTRAL_RUNE, 1), Item(Items.COSMIC_RUNE, 1), Item(Items.MIND_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    HUMIDIFY(
        interfaceId = 430,
        component = 29,
        uniqueId = 578,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Humidify",
        level = 68,
        runes = listOf(Item(Items.ASTRAL_RUNE, 1), Item(Items.WATER_RUNE, 3), Item(Items.FIRE_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    HUNTER_KIT(
        interfaceId = 430,
        component = 30,
        uniqueId = 579,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Hunter Kit",
        level = 71,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.EARTH_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    STAT_SPY(
        interfaceId = 430,
        component = 31,
        uniqueId = 576,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Stat Spy",
        level = 75,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.COSMIC_RUNE, 2), Item(Items.BODY_RUNE, 5)),
        sound = -1,
        hitSound = -1,
    ),
    DREAM(
        interfaceId = 430,
        component = 32,
        uniqueId = 580,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Dream",
        level = 79,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.COSMIC_RUNE, 1), Item(Items.BODY_RUNE, 5)),
        sound = -1,
        hitSound = -1,
    ),
    PLANK_MAKE(
        interfaceId = 430,
        component = 33,
        uniqueId = 581,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Plank Make",
        level = 86,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.EARTH_RUNE, 15), Item(Items.NATURE_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    SPELLBOOK_SWAP(
        interfaceId = 430,
        component = 34,
        uniqueId = 582,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Spellbook Swap",
        level = 96,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.COSMIC_RUNE, 2), Item(Items.LAW_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    MAGIC_IMBUE(
        interfaceId = 430,
        component = 36,
        uniqueId = 552,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Magic Imbue",
        level = 82,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.FIRE_RUNE, 7), Item(Items.WATER_RUNE, 7)),
        sound = -1,
        hitSound = -1,
    ),
    VENGEANCE(
        interfaceId = 430,
        component = 37,
        uniqueId = 564,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Vengeance",
        level = 94,
        runes = listOf(Item(Items.ASTRAL_RUNE, 4), Item(Items.DEATH_RUNE, 2), Item(Items.EARTH_RUNE, 10)),
        sound = -1,
        hitSound = -1,
    ),
    BAKE_PIE(
        interfaceId = 430,
        component = 38,
        uniqueId = 543,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Bake Pie",
        level = 65,
        runes = listOf(Item(Items.ASTRAL_RUNE, 1), Item(Items.FIRE_RUNE, 5), Item(Items.WATER_RUNE, 4)),
        sound = -1,
        hitSound = -1,
    ),
    LUNAR_HOME_TELEPORT(
        interfaceId = 430,
        component = 39,
        uniqueId = 200356,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Lunar Home Teleport",
        level = 0,
        sound = -1,
        hitSound = -1,
    ),
    FISHING_GUILD_TELEPORT(
        interfaceId = 430,
        component = 40,
        uniqueId = 555,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Fishing Guild Teleport",
        level = 85,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.LAW_RUNE, 3), Item(Items.WATER_RUNE, 8)),
        sound = -1,
        hitSound = -1,
    ),
    KHAZARD_TELEPORT(
        interfaceId = 430,
        component = 41,
        uniqueId = 549,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Khazard Teleport",
        level = 78,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.LAW_RUNE, 2), Item(Items.WATER_RUNE, 4)),
        sound = -1,
        hitSound = -1,
    ),
    VENGEANCE_OTHER(
        interfaceId = 430,
        component = 42,
        uniqueId = 561,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Vengeance Other",
        level = 93,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.DEATH_RUNE, 2), Item(Items.EARTH_RUNE, 10)),
        sound = -1,
        hitSound = -1,
    ),
    MOONCLAN_TELEPORT(
        interfaceId = 430,
        component = 43,
        uniqueId = 544,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Moonclan Teleport",
        level = 69,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.LAW_RUNE, 1), Item(Items.EARTH_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    CATHERBY_TELEPORT(
        interfaceId = 430,
        component = 44,
        uniqueId = 556,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Catherby Teleport",
        level = 87,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.LAW_RUNE, 3), Item(Items.WATER_RUNE, 10)),
        sound = -1,
        hitSound = -1,
    ),
    STRING_JEWELLERY(
        interfaceId = 430,
        component = 45,
        uniqueId = 550,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "String Jewellery",
        level = 80,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.EARTH_RUNE, 10), Item(Items.WATER_RUNE, 5)),
        sound = -1,
        hitSound = -1,
    ),
    CURE_ME(
        interfaceId = 430,
        component = 46,
        uniqueId = 562,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Cure Me",
        level = 71,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.COSMIC_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    WATERBIRTH_TELEPORT(
        interfaceId = 430,
        component = 47,
        uniqueId = 545,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Waterbirth Teleport",
        level = 72,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.LAW_RUNE, 1), Item(Items.WATER_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    SUPERGLASS_MAKE(
        interfaceId = 430,
        component = 48,
        uniqueId = 548,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Superglass Make",
        level = 77,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.FIRE_RUNE, 6), Item(Items.AIR_RUNE, 10)),
        sound = -1,
        hitSound = -1,
    ),
    BOOST_POTION_SHARE(
        interfaceId = 430,
        component = 49,
        uniqueId = 551,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Boost Potion Share",
        level = 84,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.EARTH_RUNE, 12), Item(Items.WATER_RUNE, 10)),
        sound = -1,
        hitSound = -1,
    ),
    STAT_RESTORE_POT_SHARE(
        interfaceId = 430,
        component = 50,
        uniqueId = 554,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Stat Restore Pot Share",
        level = 81,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.EARTH_RUNE, 10), Item(Items.WATER_RUNE, 10)),
        sound = -1,
        hitSound = -1,
    ),
    ICE_PLATEAU_TELEPORT(
        interfaceId = 430,
        component = 51,
        uniqueId = 557,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Ice Plateau Teleport",
        level = 89,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.LAW_RUNE, 3), Item(Items.WATER_RUNE, 8)),
        sound = -1,
        hitSound = -1,
    ),
    HEAL_OTHER(
        interfaceId = 430,
        component = 52,
        uniqueId = 560,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Heal Other",
        level = 92,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.LAW_RUNE, 3), Item(Items.BLOOD_RUNE, 1)),
        sound = -1,
        hitSound = -1,
    ),
    HEAL_GROUP(
        interfaceId = 430,
        component = 53,
        uniqueId = 566,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Heal Group",
        level = 95,
        runes = listOf(Item(Items.ASTRAL_RUNE, 4), Item(Items.BLOOD_RUNE, 2), Item(Items.LAW_RUNE, 3)),
        sound = -1,
        hitSound = -1,
    ),
    OURANIA_TELEPORT(
        interfaceId = 430,
        component = 54,
        uniqueId = 583,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Ourania Teleport",
        level = 71,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.LAW_RUNE, 1), Item(Items.EARTH_RUNE, 6)),
        sound = -1,
        hitSound = -1,
    ),
    CURE_PLANT(
        interfaceId = 430,
        component = 55,
        uniqueId = 567,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Cure Plant",
        level = 66,
        runes = listOf(Item(Items.ASTRAL_RUNE, 1), Item(Items.EARTH_RUNE, 8)),
        sound = -1,
        hitSound = -1,
    ),
    TELE_GROUP_MOONCLAN(
        interfaceId = 430,
        component = 56,
        uniqueId = 569,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Tele Group Moonclan",
        level = 70,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.LAW_RUNE, 1), Item(Items.EARTH_RUNE, 4)),
        sound = -1,
        hitSound = -1,
    ),
    TELE_GROUP_WATERBIRTH(
        interfaceId = 430,
        component = 57,
        uniqueId = 570,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Tele Group Waterbirth",
        level = 73,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.LAW_RUNE, 1), Item(Items.WATER_RUNE, 5)),
        sound = -1,
        hitSound = -1,
    ),
    TELE_GROUP_BARBARIAN(
        interfaceId = 430,
        component = 58,
        uniqueId = 571,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Tele Group Barbarian",
        level = 76,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.LAW_RUNE, 2), Item(Items.FIRE_RUNE, 6)),
        sound = -1,
        hitSound = -1,
    ),
    TELE_GROUP_KHAZARD(
        interfaceId = 430,
        component = 59,
        uniqueId = 572,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Tele Group Khazard",
        level = 79,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.LAW_RUNE, 2), Item(Items.WATER_RUNE, 8)),
        sound = -1,
        hitSound = -1,
    ),
    TELE_GROUP_FISHING_GUILD(
        interfaceId = 430,
        component = 60,
        uniqueId = 573,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Tele Group Fishing Guild",
        level = 86,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.LAW_RUNE, 3), Item(Items.WATER_RUNE, 10)),
        sound = -1,
        hitSound = -1,
    ),
    TELE_GROUP_CATHERBY(
        interfaceId = 430,
        component = 61,
        uniqueId = 574,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Tele Group Catherby",
        level = 88,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.LAW_RUNE, 3), Item(Items.WATER_RUNE, 12)),
        sound = -1,
        hitSound = -1,
    ),
    TELE_GROUP_ICE_PLATEAU(
        interfaceId = 430,
        component = 62,
        uniqueId = 575,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Tele Group Ice Plateau",
        level = 90,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.LAW_RUNE, 3), Item(Items.WATER_RUNE, 16)),
        sound = -1,
        hitSound = -1,
    ),
    SOUTH_FALADOR_TELEPORT(
        interfaceId = 430,
        component = 67,
        uniqueId = 4585,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "South Falador Teleport",
        level = 72,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.LAW_RUNE, 1), Item(Items.AIR_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    NORTH_ARDOUGNE_TELEPORT(
        interfaceId = 430,
        component = 69,
        uniqueId = 4587,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "North Ardougne Teleport",
        level = 76,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.LAW_RUNE, 1), Item(Items.WATER_RUNE, 5)),
        sound = -1,
        hitSound = -1,
    ),
    REMOTE_FARM(
        interfaceId = 430,
        component = 70,
        uniqueId = 4588,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Remote Farm",
        level = 78,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.EARTH_RUNE, 2), Item(Items.NATURE_RUNE, 3)),
        sound = -1,
        hitSound = -1,
    ),
    SPIRITUALISE_FOOD(
        interfaceId = 430,
        component = 71,
        uniqueId = 4590,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Spiritualise Food",
        level = 80,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.COSMIC_RUNE, 3), Item(Items.BODY_RUNE, 5)),
        sound = -1,
        hitSound = -1,
    ),
    MAKE_LEATHER(
        interfaceId = 430,
        component = 72,
        uniqueId = 4589,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Make Leather",
        level = 83,
        runes = listOf(Item(Items.ASTRAL_RUNE, 2), Item(Items.FIRE_RUNE, 2), Item(Items.BODY_RUNE, 2)),
        sound = -1,
        hitSound = -1,
    ),
    DISRUPTION_SHIELD(
        interfaceId = 430,
        component = 73,
        uniqueId = 4591,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Disruption Shield",
        level = 90,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.BLOOD_RUNE, 3), Item(Items.BODY_RUNE, 10)),
        sound = -1,
        hitSound = -1,
    ),
    VENGEANCE_GROUP(
        interfaceId = 430,
        component = 74,
        uniqueId = 4592,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Vengeance Group",
        level = 95,
        runes = listOf(Item(Items.ASTRAL_RUNE, 4), Item(Items.DEATH_RUNE, 3), Item(Items.EARTH_RUNE, 11)),
        sound = -1,
        hitSound = -1,
    ),
    LUNAR_TROLLHEIM_TELEPORT(
        interfaceId = 430,
        component = 75,
        uniqueId = 7685,
        spellType = SpellType.TELEPORT_SPELL_TYPE,
        spellName = "Trollheim Teleport",
        level = 92,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.LAW_RUNE, 3), Item(Items.WATER_RUNE, 10)),
        sound = -1,
        hitSound = -1,
    ),
    TELE_GROUP_TROLLHEIM(
        interfaceId = 430,
        component = 76,
        uniqueId = 7686,
        spellType = SpellType.MISC_SPELL_TYPE,
        spellName = "Tele Group Trollheim",
        level = 93,
        runes = listOf(Item(Items.ASTRAL_RUNE, 3), Item(Items.LAW_RUNE, 3), Item(Items.WATER_RUNE, 20)),
        sound = -1,
        hitSound = -1,
    ),
}
