package gg.rsmod.plugins.content.mechanics.shops

import com.google.gson.JsonParser
import gg.rsmod.game.fs.def.ItemDef
import gg.rsmod.game.fs.def.NpcDef
import gg.rsmod.game.model.shop.PurchasePolicy
import gg.rsmod.game.model.shop.ShopItem
import java.io.File
import java.io.FileReader

/**
 * Owner 2026-09-23: "trading some npcs bartenders and other npcs nothing interesting happens fix this for every NPC".
 *
 * The npcs whose cache Trade/Shop/Buy option still had no handler after the hand-written shops and the 2009scape bulk import
 * (npc_inventory.csv census) get the shop the RuneScape Wiki gives them: `data/cfg/shops/wiki-shops.json`, generated by
 * `C:\RSPS\tools\npc-dialogue\fetch_wiki_shops.py` (npc id -> wiki npc page -> its shop page's store table: items, stock, the
 * wiki's own sell price and currency; each row records its page and revision). Bound after bulk_shops, only on options that are
 * still free; a title that already exists keeps its own stock and just gains the keeper.
 *
 * Not bound: Perdu (14394) - his Lost Property service returns the player's own lost items and needs ownership rules, not a
 * shop that sells them to anyone (WORK_QUEUE 1b.1). Shops paid in minigame points that are not items here are not generated.
 */
val WIKI_SHOPS_PATH = "./data/cfg/shops/wiki-shops.json"
val EXCLUDED_KEEPERS = setOf(14394)

on_world_init_late {
    val file = File(WIKI_SHOPS_PATH)
    if (!file.exists()) return@on_world_init_late
    val shops = FileReader(file).use { JsonParser().parse(it).asJsonArray }
    val itemCount = world.definitions.getCount(ItemDef::class.java)
    var created = 0
    var bound = 0
    shops.forEach { el ->
        val shop = el.asJsonObject
        val title = shop["title"].asString
        val keepers =
            shop.getAsJsonArray("npcs").map { it.asInt }.filter { it !in EXCLUDED_KEEPERS }.mapNotNull { id ->
                if (id < 0 || id >= world.definitions.getCount(NpcDef::class.java)) return@mapNotNull null
                val def = world.definitions.get(NpcDef::class.java, id)
                val slot = def.options.indexOfFirst { it != null && it.lowercase() in setOf("trade", "trade-with", "shop", "buy") }
                if (slot == -1 || world.plugins.boundNpcOptions(id).contains(slot + 1)) null else id to slot + 1
            }
        if (keepers.isEmpty()) return@forEach
        if (world.getShop(title) == null) {
            val stock =
                shop.getAsJsonArray("stock").map { it.asJsonArray }
                    .filter { it[0].asInt in 0 until itemCount }
                    .distinctBy { it[0].asInt }
            if (stock.isEmpty()) return@forEach
            val currencyItem = shop["currency"].asInt
            val currencyName = world.definitions.get(ItemDef::class.java, currencyItem).name.lowercase()
            create_shop(
                title,
                currency = if (currencyItem == Items.COINS_995) CoinCurrency() else ItemCurrency(currencyItem, currencyName, currencyName.removeSuffix("s") + "s"),
                purchasePolicy = PurchasePolicy.BUY_STOCK,
                stockSize = maxOf(40, stock.size),
                containsSamples = false,
            ) {
                stock.forEachIndexed { index, row -> items[index] = ShopItem(row[0].asInt, row[1].asInt, sellPrice = row[2].asInt) }
            }
            created++
        }
        keepers.forEach { (id, slot) ->
            world.plugins.bindNpc(id, slot) { player.openShop(title) }
            bound++
        }
    }
    println("wiki_shops: created $created shops, bound $bound keepers.")
}
