package gg.rsmod.plugins.content.items.armor

import gg.rsmod.plugins.api.cfg.Items

/** PvP / corrupt armour combat charge budgets; the degrading itself runs in [EquipmentDegradation] (RCV-011 Q-019). */
object CorruptArmorCharges {
    const val SIXTY_MINUTE_CHARGE = 6_000
    const val THIRTY_MINUTE_CHARGE = 3_000
    const val FIFTEEN_MINUTE_CHARGE = 1_500
}

enum class CorruptArmor(val newId: Int, val degradedId: Int, val maxCharges: Int) {
    // These have 30 minutes of charge
    CORRUPT_DRAGON_BATTLEAXE(
        Items.CORRUPT_DRAGON_BATTLEAXE,
        Items.C_DRAGON_BATTLEAXE_DEG,
        CorruptArmorCharges.THIRTY_MINUTE_CHARGE
    ),
    CORRUPT_DRAGON_DAGGER(
        Items.CORRUPT_DRAGON_DAGGER,
        Items.C_DRAGON_DAGGER_DEG,
        CorruptArmorCharges.THIRTY_MINUTE_CHARGE
    ),
    CORRUPT_DRAGON_LONGSWORD(
        Items.CORRUPT_DRAGON_LONGSWORD,
        Items.C_DRAGON_LONGSWORD_DEG,
        CorruptArmorCharges.THIRTY_MINUTE_CHARGE
    ),
    CORRUPT_DRAGON_MACE(
        Items.CORRUPT_DRAGON_MACE,
        Items.CORRUPT_DRAGON_MACE_DEG,
        CorruptArmorCharges.THIRTY_MINUTE_CHARGE
    ),
    CORRUPT_DRAGON_SCIMITAR(
        Items.CORRUPT_DRAGON_SCIMITAR,
        Items.C_DRAGON_SCIMITAR_DEG,
        CorruptArmorCharges.THIRTY_MINUTE_CHARGE
    ),
    CORRUPT_DRAGON_SPEAR(
        Items.CORRUPT_DRAGON_SPEAR,
        Items.CORRUPT_DRAGON_SPEAR_DEG,
        CorruptArmorCharges.THIRTY_MINUTE_CHARGE
    ),
    CORRUPT_DRAGON_CHAINBODY(
        Items.CORRUPT_DRAGON_CHAINBODY,
        Items.CORRUPT_DRAGON_CHAINBODY_DEG,
        CorruptArmorCharges.THIRTY_MINUTE_CHARGE
    ),
    CORRUPT_DRAGON_MED_HELM(
        Items.CORRUPT_DRAGON_MED_HELM,
        Items.CORRUPT_DRAGON_MED_HELM_DEG,
        CorruptArmorCharges.THIRTY_MINUTE_CHARGE
    ),
    CORRUPT_DRAGON_PLATELEGS(
        Items.CORRUPT_DRAGON_PLATELEGS,
        Items.CORRUPT_DRAGON_PLATELEGS_DEG,
        CorruptArmorCharges.THIRTY_MINUTE_CHARGE
    ),
    CORRUPT_DRAGON_PLATESKIRT(
        Items.CORRUPT_DRAGON_PLATESKIRT,
        Items.CORRUPT_DRAGON_PLATESKIRT_DEG,
        CorruptArmorCharges.THIRTY_MINUTE_CHARGE
    ),
    CORRUPT_DRAGON_SQ_SHIELD(
        Items.CORRUPT_DRAGON_SQ_SHIELD,
        Items.CORRUPT_DRAGON_SQ_SHIELD_DEG,
        CorruptArmorCharges.THIRTY_MINUTE_CHARGE
    ),
    // These have 15 minutes of charge
    CORRUPT_STATIUSS_WARHAMMER(
        Items.CORRUPT_STATIUSS_WARHAMMER,
        Items.C_STATIUSS_WARHAMMER_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_VESTAS_LONGSWORD(
        Items.CORRUPT_VESTAS_LONGSWORD,
        Items.C_VESTAS_LONGSWORD_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_VESTAS_SPEAR(
        Items.CORRUPT_VESTAS_SPEAR,
        Items.CORRUPT_VESTAS_SPEAR_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_ZURIELS_STAFF(
        Items.CORRUPT_ZURIELS_STAFF,
        Items.CORRUPT_ZURIELS_STAFF_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_MORRIGANS_COIF(
        Items.CORRUPT_MORRIGANS_COIF,
        Items.CORRUPT_MORRIGANS_COIF_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_MORRIGANS_LEATHER_BODY(
        Items.CORRUPT_MORRIGANS_LEATHER_BODY,
        Items.CORRUPT_MORRIGANS_LEATHER_BODY_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_MORRIGANS_LEATHER_CHAPS(
        Items.CORRUPT_MORRIGANS_LEATHER_CHAPS,
        Items.CORRUPT_MORRIGANS_LEATHER_CHAPS_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_STATIUSS_FULL_HELM(
        Items.CORRUPT_STATIUSS_FULL_HELM,
        Items.CORRUPT_STATIUS_FULL_HELM_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_STATIUSS_PLATEBODY(
        Items.CORRUPT_STATIUSS_PLATEBODY,
        Items.CORRUPT_STATIUSS_PLATEBODY_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_STATIUSS_PLATELEGS(
        Items.CORRUPT_STATIUSS_PLATELEGS,
        Items.CORRUPT_STATIUSS_PLATELEGS_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_VESTAS_CHAINBODY(
        Items.CORRUPT_VESTAS_CHAINBODY,
        Items.CORRUPT_VESTAS_CHAINBODY_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_VESTAS_PLATESKIRT(
        Items.CORRUPT_VESTAS_PLATESKIRT,
        Items.CORRUPT_VESTAS_PLATESKIRT_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_ZURIELS_HOOD(
        Items.CORRUPT_ZURIELS_HOOD,
        Items.CORRUPT_ZURIELS_HOOD_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_ZURIELS_ROBE_TOP(
        Items.CORRUPT_ZURIELS_ROBE_TOP,
        Items.CORRUPT_ZURIELS_ROBE_TOP_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),
    CORRUPT_ZURIELS_ROBE_BOTTOM(
        Items.CORRUPT_ZURIELS_ROBE_BOTTOM,
        Items.CORRUPT_ZURIELS_ROBE_BOTTOM_DEG,
        CorruptArmorCharges.FIFTEEN_MINUTE_CHARGE
    ),

    // These have 60 minute charge
    STATIUSS_WARHAMMER(
        Items.STATIUSS_WARHAMMER,
        Items.STATIUS_WARHAMMER_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    VESTAS_LONGSWORD(
        Items.VESTAS_LONGSWORD,
        Items.VESTAS_LONGSWORD_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    VESTAS_SPEAR(
        Items.VESTAS_SPEAR,
        Items.VESTAS_SPEAR_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    ZURIELS_STAFF(
        Items.ZURIELS_STAFF,
        Items.ZURIELS_STAFF_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    MORRIGANS_COIF(
        Items.MORRIGANS_COIF,
        Items.MORRIGANS_COIF_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    MORRIGANS_LEATHER_BODY(
        Items.MORRIGANS_LEATHER_BODY,
        Items.MORRIGANS_LEATHER_BODY_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    MORRIGANS_LEATHER_CHAPS(
        Items.MORRIGANS_LEATHER_CHAPS,
        Items.MORRIGANS_LEATHER_CHAPS_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    STATIUSS_FULL_HELM(
        Items.STATIUSS_FULL_HELM,
        Items.STATIUS_FULL_HELM_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    STATIUSS_PLATEBODY(
        Items.STATIUSS_PLATEBODY,
        Items.STATIUSS_PLATEBODY_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    STATIUSS_PLATELEGS(
        Items.STATIUSS_PLATELEGS,
        Items.STATIUSS_PLATELEGS_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    VESTAS_CHAINBODY(
        Items.VESTAS_CHAINBODY,
        Items.VESTAS_CHAINBODY_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    VESTAS_PLATESKIRT(
        Items.VESTAS_PLATESKIRT,
        Items.VESTAS_PLATESKIRT_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    ZURIELS_HOOD(
        Items.ZURIELS_HOOD,
        Items.ZURIELS_HOOD_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    ZURIELS_ROBE_TOP(
        Items.ZURIELS_ROBE_TOP,
        Items.ZURIELS_ROBE_TOP_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
    ZURIELS_ROBE_BOTTOM(
        Items.ZURIELS_ROBE_BOTTOM,
        Items.ZURIELS_ROBE_BOTTOM_DEG,
        CorruptArmorCharges.SIXTY_MINUTE_CHARGE
    ),
}
